#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --account=nvr_lpr_rvp
#SBATCH --gpus-per-node=1
#SBATCH --job-name=dextrah_franka_multi_vid
#SBATCH --partition=batch
#SBATCH --time=0-00:45:00
#SBATCH --mem=128G
#SBATCH --cpus-per-task=16
#SBATCH --output=/lustre/fsw/portfolios/nvr/users/lzha/slurm_logs/dextrah/validate_franka_multi_object_videos_%j.out

set -euo pipefail

NFS_ROOT="${NFS_ROOT:-/lustre/fsw/portfolios/nvr/users/lzha}"
CODE_NFS="${CODE_NFS:-$NFS_ROOT/src/DEXTRAH}"
FABRICS_NFS="${FABRICS_NFS:-$NFS_ROOT/src/FABRICS}"
ISAACLAB_NFS="${ISAACLAB_NFS:-$NFS_ROOT/src/IsaacLab-v2.2.1}"
IMAGE="${IMAGE:-$NFS_ROOT/cache/isaac_lab_2.2.0.sqsh}"
ENV_ROOT="${ENV_ROOT:-$NFS_ROOT/envs}"
ENV_NAME="${ENV_NAME:-dextrah-isaaclab}"
RESULTS_NFS="${RESULTS_NFS:-$NFS_ROOT/results/dextrah}"
CACHE_NFS="${CACHE_NFS:-$NFS_ROOT/isaac_cache}"

TASK="${TASK:-Dextrah-Franka-Multi-Object-Grasp}"
SLURM_JOB_ID_SAFE="${SLURM_JOB_ID:-manual}"
RUN_NAME="${RUN_NAME:-franka_multi_object_video_validate_${SLURM_JOB_ID_SAFE}_$(date +%Y%m%d_%H%M%S)}"
NUM_ENVS="${NUM_ENVS:-4}"
SEED="${SEED:-42}"
OBJECT_ASSET_MANIFEST_PATH="${OBJECT_ASSET_MANIFEST_PATH:-}"
MAX_OBJECTS="${MAX_OBJECTS:-4}"
OBJECT_ASSET_ASSIGNMENT="${OBJECT_ASSET_ASSIGNMENT:-round_robin}"
OBJECT_SPAWN_CENTER_OFFSET_X="${OBJECT_SPAWN_CENTER_OFFSET_X:-0.05}"
OBJECT_SPAWN_CENTER_OFFSET_Y="${OBJECT_SPAWN_CENTER_OFFSET_Y:-0.0}"
OBJECT_SPAWN_XY_RANDOMIZATION="${OBJECT_SPAWN_XY_RANDOMIZATION:-0.10}"
OBJECT_SPAWN_YAW_RANDOMIZATION_DEG="${OBJECT_SPAWN_YAW_RANDOMIZATION_DEG:-180.0}"
OBJECT_STABLE_POSE_ENABLED="${OBJECT_STABLE_POSE_ENABLED:-False}"
OBJECT_STABLE_POSE_CACHE_DIR="${OBJECT_STABLE_POSE_CACHE_DIR:-}"
OBJECT_STABLE_POSE_COUNT="${OBJECT_STABLE_POSE_COUNT:-1}"
OBJECT_STABLE_POSE_RANDOMIZE="${OBJECT_STABLE_POSE_RANDOMIZE:-True}"
OBJECT_STABLE_POSE_ALLOW_MISSING="${OBJECT_STABLE_POSE_ALLOW_MISSING:-False}"
OBJECT_DENSITY="${OBJECT_DENSITY:-}"
OBJECT_STATIC_FRICTION="${OBJECT_STATIC_FRICTION:-}"
OBJECT_DYNAMIC_FRICTION="${OBJECT_DYNAMIC_FRICTION:-}"
OBJECT_CONTACT_OFFSET="${OBJECT_CONTACT_OFFSET:-}"
OBJECT_REST_OFFSET="${OBJECT_REST_OFFSET:-}"
OBJECT_SOLVER_POSITION_ITERATIONS="${OBJECT_SOLVER_POSITION_ITERATIONS:-}"
OBJECT_SOLVER_VELOCITY_ITERATIONS="${OBJECT_SOLVER_VELOCITY_ITERATIONS:-}"
OBJECT_LINEAR_DAMPING="${OBJECT_LINEAR_DAMPING:-}"
OBJECT_ANGULAR_DAMPING="${OBJECT_ANGULAR_DAMPING:-}"
OBJECT_MAX_DEPENETRATION_VELOCITY="${OBJECT_MAX_DEPENETRATION_VELOCITY:-}"
RENDER_WARMUP_FRAMES="${RENDER_WARMUP_FRAMES:-2}"
RESET_CYCLES="${RESET_CYCLES:-3}"
SETTLE_STEPS="${SETTLE_STEPS:-72}"
PERTURB_STEPS="${PERTURB_STEPS:-96}"
PERTURB_PUSH_STEPS="${PERTURB_PUSH_STEPS:-10}"
PERTURB_LINEAR_VELOCITY="${PERTURB_LINEAR_VELOCITY:-0.60}"
PERTURB_LATERAL_VELOCITY="${PERTURB_LATERAL_VELOCITY:-0.20}"
PERTURB_ANGULAR_VELOCITY="${PERTURB_ANGULAR_VELOCITY:-4.0}"
GRASP_STEPS="${GRASP_STEPS:-72}"
GRASP_OBJECT_SETTLE_STEPS="${GRASP_OBJECT_SETTLE_STEPS:-48}"
OBJECT_RESET_SETTLE_STEPS="${OBJECT_RESET_SETTLE_STEPS:-120}"
GRASP_WARMSTART_CLOSE_WIDTH="${GRASP_WARMSTART_CLOSE_WIDTH:-0.025}"
GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH="${GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH:-True}"
GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN="${GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN:-0.003}"
GRASP_WARMSTART_MIN_CLOSE_WIDTH="${GRASP_WARMSTART_MIN_CLOSE_WIDTH:-0.0}"
GRASP_WARMSTART_LIFT_ACTION_Z="${GRASP_WARMSTART_LIFT_ACTION_Z:-0.30}"
GRASP_WARMSTART_APPROACH_STEPS="${GRASP_WARMSTART_APPROACH_STEPS:-0}"
GRASP_WARMSTART_CLOSE_STEPS="${GRASP_WARMSTART_CLOSE_STEPS:-0}"
GRASP_WARMSTART_LIFT_STEPS="${GRASP_WARMSTART_LIFT_STEPS:-0}"
GRASP_WARMSTART_GAIN="${GRASP_WARMSTART_GAIN:-8.0}"
GRASP_WARMSTART_MAX_POSITION_ACTION="${GRASP_WARMSTART_MAX_POSITION_ACTION:-1.0}"
GRASP_WARMSTART_TRACK_ORIENTATION="${GRASP_WARMSTART_TRACK_ORIENTATION:-True}"
GRASP_WARMSTART_CLOSE_MAX_EE_ERROR="${GRASP_WARMSTART_CLOSE_MAX_EE_ERROR:-0.0}"
GRASP_WARMSTART_LIFT_MAX_EE_ERROR="${GRASP_WARMSTART_LIFT_MAX_EE_ERROR:-0.0}"
GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST="${GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST:-0.0}"
GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN="${GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN:--1.0}"
GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY="${GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY:-}"
CAPTURE_INTERVAL="${CAPTURE_INTERVAL:-2}"
GRASP_RESET_ATTEMPTS="${GRASP_RESET_ATTEMPTS:-12}"
GRASP_RESET_REQUIRE_TOPDOWN="${GRASP_RESET_REQUIRE_TOPDOWN:-True}"
GRASP_RESET_MIN_PREGRASP_Z="${GRASP_RESET_MIN_PREGRASP_Z:-0.70}"
GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER="${GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER:-0.0}"
GRASP_RESET_CANDIDATE_COUNT="${GRASP_RESET_CANDIDATE_COUNT:-16}"
GRASP_RESET_MAX_CENTER_DISTANCE_FRAC="${GRASP_RESET_MAX_CENTER_DISTANCE_FRAC:-0.30}"
GRASP_RESET_MIN_WIDTH="${GRASP_RESET_MIN_WIDTH:-0.008}"
GRASP_PRIOR_VERIFIED_INDICES_PATH="${GRASP_PRIOR_VERIFIED_INDICES_PATH:-}"
GRASP_RESET_IK_ITERATIONS="${GRASP_RESET_IK_ITERATIONS:-}"
GRASP_RESET_IK_DAMPING="${GRASP_RESET_IK_DAMPING:-}"
GRASP_RESET_IK_MAX_JOINT_STEP="${GRASP_RESET_IK_MAX_JOINT_STEP:-}"
GRASP_RESET_IK_POS_TOLERANCE="${GRASP_RESET_IK_POS_TOLERANCE:-}"
GRASP_RESET_IK_ROT_TOLERANCE="${GRASP_RESET_IK_ROT_TOLERANCE:-}"
GRASP_PREGRASP_OFFSET="${GRASP_PREGRASP_OFFSET:-}"
GRASP_CONTACT_SCORE_STEPS="${GRASP_CONTACT_SCORE_STEPS:-60}"
CODE_COMMIT="${CODE_COMMIT:-}"
if [ -z "$CODE_COMMIT" ] && git -C "$CODE_NFS" rev-parse HEAD >/dev/null 2>&1; then
  CODE_COMMIT="$(git -C "$CODE_NFS" rev-parse HEAD)"
fi

RUN_DIR_HOST="$RESULTS_NFS/validations/$RUN_NAME"
RUN_DIR_CONTAINER="/results/validations/$RUN_NAME"
METRICS_CONTAINER="$RUN_DIR_CONTAINER/video_metrics.json"
LOG_FILE="$NFS_ROOT/slurm_logs/dextrah/validate_franka_multi_object_videos_${SLURM_JOB_ID_SAFE}.out"

if [ -z "$OBJECT_ASSET_MANIFEST_PATH" ]; then
  echo "OBJECT_ASSET_MANIFEST_PATH is required"
  exit 2
fi
if [ ! -f "$IMAGE" ]; then
  echo "Missing Isaac Lab container image: $IMAGE"
  exit 2
fi
if [ ! -d "$ENV_ROOT/$ENV_NAME/site" ]; then
  echo "Missing DEXTRAH Python target: $ENV_ROOT/$ENV_NAME/site"
  exit 2
fi

mkdir -p \
  "$RUN_DIR_HOST" \
  "$NFS_ROOT/slurm_logs/dextrah" \
  "$CACHE_NFS/kit" "$CACHE_NFS/ov" "$CACHE_NFS/pip" \
  "$CACHE_NFS/glcache" "$CACHE_NFS/computecache" \
  "$CACHE_NFS/omni_logs" "$CACHE_NFS/carb_logs" \
  "$CACHE_NFS/data" "$CACHE_NFS/documents"

export TASK RUN_NAME NUM_ENVS SEED OBJECT_ASSET_MANIFEST_PATH MAX_OBJECTS OBJECT_ASSET_ASSIGNMENT
export OBJECT_SPAWN_CENTER_OFFSET_X OBJECT_SPAWN_CENTER_OFFSET_Y OBJECT_SPAWN_XY_RANDOMIZATION
export OBJECT_SPAWN_YAW_RANDOMIZATION_DEG RENDER_WARMUP_FRAMES
export OBJECT_STABLE_POSE_ENABLED OBJECT_STABLE_POSE_CACHE_DIR OBJECT_STABLE_POSE_COUNT
export OBJECT_STABLE_POSE_RANDOMIZE OBJECT_STABLE_POSE_ALLOW_MISSING
export OBJECT_DENSITY OBJECT_STATIC_FRICTION OBJECT_DYNAMIC_FRICTION
export OBJECT_CONTACT_OFFSET OBJECT_REST_OFFSET
export OBJECT_SOLVER_POSITION_ITERATIONS OBJECT_SOLVER_VELOCITY_ITERATIONS
export OBJECT_LINEAR_DAMPING OBJECT_ANGULAR_DAMPING OBJECT_MAX_DEPENETRATION_VELOCITY
export RESET_CYCLES SETTLE_STEPS PERTURB_STEPS PERTURB_PUSH_STEPS
export PERTURB_LINEAR_VELOCITY PERTURB_LATERAL_VELOCITY PERTURB_ANGULAR_VELOCITY
export GRASP_STEPS GRASP_OBJECT_SETTLE_STEPS CAPTURE_INTERVAL GRASP_RESET_ATTEMPTS GRASP_RESET_MIN_PREGRASP_Z
export GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER
export GRASP_RESET_REQUIRE_TOPDOWN
export GRASP_RESET_CANDIDATE_COUNT
export GRASP_RESET_MAX_CENTER_DISTANCE_FRAC
export GRASP_RESET_MIN_WIDTH
export GRASP_PRIOR_VERIFIED_INDICES_PATH
export GRASP_RESET_IK_ITERATIONS GRASP_RESET_IK_DAMPING GRASP_RESET_IK_MAX_JOINT_STEP
export GRASP_RESET_IK_POS_TOLERANCE GRASP_RESET_IK_ROT_TOLERANCE
export GRASP_PREGRASP_OFFSET
export GRASP_CONTACT_SCORE_STEPS
export OBJECT_RESET_SETTLE_STEPS
export GRASP_WARMSTART_CLOSE_WIDTH GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH
export GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN GRASP_WARMSTART_MIN_CLOSE_WIDTH
export GRASP_WARMSTART_LIFT_ACTION_Z GRASP_WARMSTART_APPROACH_STEPS GRASP_WARMSTART_CLOSE_STEPS
export GRASP_WARMSTART_LIFT_STEPS GRASP_WARMSTART_GAIN GRASP_WARMSTART_MAX_POSITION_ACTION
export GRASP_WARMSTART_TRACK_ORIENTATION GRASP_WARMSTART_CLOSE_MAX_EE_ERROR
export GRASP_WARMSTART_LIFT_MAX_EE_ERROR GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST
export GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN
export GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY
export RUN_DIR_CONTAINER METRICS_CONTAINER ENV_NAME CODE_COMMIT

echo "Running DextrAH Franka multi-object video validation"
echo "SLURM_JOB_ID=$SLURM_JOB_ID_SAFE"
echo "SLURM_JOB_NODELIST=${SLURM_JOB_NODELIST:-unset}"
echo "IMAGE=$IMAGE"
echo "CODE_NFS=$CODE_NFS"
echo "FABRICS_NFS=$FABRICS_NFS"
echo "ISAACLAB_NFS=$ISAACLAB_NFS"
echo "CODE_COMMIT=${CODE_COMMIT:-unknown}"
echo "RESULTS_NFS=$RESULTS_NFS"
echo "TASK=$TASK"
echo "RUN_NAME=$RUN_NAME"
echo "NUM_ENVS=$NUM_ENVS"
echo "SEED=$SEED"
echo "OBJECT_ASSET_MANIFEST_PATH=$OBJECT_ASSET_MANIFEST_PATH"
echo "MAX_OBJECTS=$MAX_OBJECTS"
echo "OBJECT_ASSET_ASSIGNMENT=$OBJECT_ASSET_ASSIGNMENT"
echo "OBJECT_SPAWN_CENTER_OFFSET_X=$OBJECT_SPAWN_CENTER_OFFSET_X"
echo "OBJECT_SPAWN_CENTER_OFFSET_Y=$OBJECT_SPAWN_CENTER_OFFSET_Y"
echo "OBJECT_SPAWN_XY_RANDOMIZATION=$OBJECT_SPAWN_XY_RANDOMIZATION"
echo "OBJECT_SPAWN_YAW_RANDOMIZATION_DEG=$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
echo "OBJECT_STABLE_POSE_ENABLED=$OBJECT_STABLE_POSE_ENABLED"
echo "OBJECT_STABLE_POSE_CACHE_DIR=$OBJECT_STABLE_POSE_CACHE_DIR"
echo "OBJECT_STABLE_POSE_COUNT=$OBJECT_STABLE_POSE_COUNT"
echo "OBJECT_STABLE_POSE_RANDOMIZE=$OBJECT_STABLE_POSE_RANDOMIZE"
echo "OBJECT_STABLE_POSE_ALLOW_MISSING=$OBJECT_STABLE_POSE_ALLOW_MISSING"
echo "OBJECT_DENSITY=$OBJECT_DENSITY"
echo "OBJECT_STATIC_FRICTION=$OBJECT_STATIC_FRICTION"
echo "OBJECT_DYNAMIC_FRICTION=$OBJECT_DYNAMIC_FRICTION"
echo "OBJECT_CONTACT_OFFSET=$OBJECT_CONTACT_OFFSET"
echo "OBJECT_REST_OFFSET=$OBJECT_REST_OFFSET"
echo "OBJECT_SOLVER_POSITION_ITERATIONS=$OBJECT_SOLVER_POSITION_ITERATIONS"
echo "OBJECT_SOLVER_VELOCITY_ITERATIONS=$OBJECT_SOLVER_VELOCITY_ITERATIONS"
echo "OBJECT_LINEAR_DAMPING=$OBJECT_LINEAR_DAMPING"
echo "OBJECT_ANGULAR_DAMPING=$OBJECT_ANGULAR_DAMPING"
echo "OBJECT_MAX_DEPENETRATION_VELOCITY=$OBJECT_MAX_DEPENETRATION_VELOCITY"
echo "RESET_CYCLES=$RESET_CYCLES"
echo "SETTLE_STEPS=$SETTLE_STEPS"
echo "PERTURB_STEPS=$PERTURB_STEPS"
echo "PERTURB_PUSH_STEPS=$PERTURB_PUSH_STEPS"
echo "PERTURB_LINEAR_VELOCITY=$PERTURB_LINEAR_VELOCITY"
echo "PERTURB_LATERAL_VELOCITY=$PERTURB_LATERAL_VELOCITY"
echo "PERTURB_ANGULAR_VELOCITY=$PERTURB_ANGULAR_VELOCITY"
echo "GRASP_STEPS=$GRASP_STEPS"
echo "GRASP_OBJECT_SETTLE_STEPS=$GRASP_OBJECT_SETTLE_STEPS"
echo "OBJECT_RESET_SETTLE_STEPS=$OBJECT_RESET_SETTLE_STEPS"
echo "GRASP_WARMSTART_CLOSE_WIDTH=$GRASP_WARMSTART_CLOSE_WIDTH"
echo "GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH=$GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH"
echo "GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN=$GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
echo "GRASP_WARMSTART_MIN_CLOSE_WIDTH=$GRASP_WARMSTART_MIN_CLOSE_WIDTH"
echo "GRASP_WARMSTART_LIFT_ACTION_Z=$GRASP_WARMSTART_LIFT_ACTION_Z"
echo "GRASP_WARMSTART_APPROACH_STEPS=$GRASP_WARMSTART_APPROACH_STEPS"
echo "GRASP_WARMSTART_CLOSE_STEPS=$GRASP_WARMSTART_CLOSE_STEPS"
echo "GRASP_WARMSTART_LIFT_STEPS=$GRASP_WARMSTART_LIFT_STEPS"
echo "GRASP_WARMSTART_GAIN=$GRASP_WARMSTART_GAIN"
echo "GRASP_WARMSTART_MAX_POSITION_ACTION=$GRASP_WARMSTART_MAX_POSITION_ACTION"
echo "GRASP_WARMSTART_TRACK_ORIENTATION=$GRASP_WARMSTART_TRACK_ORIENTATION"
echo "GRASP_WARMSTART_CLOSE_MAX_EE_ERROR=$GRASP_WARMSTART_CLOSE_MAX_EE_ERROR"
echo "GRASP_WARMSTART_LIFT_MAX_EE_ERROR=$GRASP_WARMSTART_LIFT_MAX_EE_ERROR"
echo "GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST=$GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
echo "GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN=$GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
echo "GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY=$GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY"
echo "CAPTURE_INTERVAL=$CAPTURE_INTERVAL"
echo "GRASP_RESET_ATTEMPTS=$GRASP_RESET_ATTEMPTS"
echo "GRASP_RESET_REQUIRE_TOPDOWN=$GRASP_RESET_REQUIRE_TOPDOWN"
echo "GRASP_RESET_MIN_PREGRASP_Z=$GRASP_RESET_MIN_PREGRASP_Z"
echo "GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER=$GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER"
echo "GRASP_RESET_CANDIDATE_COUNT=$GRASP_RESET_CANDIDATE_COUNT"
echo "GRASP_RESET_MAX_CENTER_DISTANCE_FRAC=$GRASP_RESET_MAX_CENTER_DISTANCE_FRAC"
echo "GRASP_RESET_MIN_WIDTH=$GRASP_RESET_MIN_WIDTH"
echo "GRASP_PRIOR_VERIFIED_INDICES_PATH=$GRASP_PRIOR_VERIFIED_INDICES_PATH"
echo "GRASP_RESET_IK_ITERATIONS=$GRASP_RESET_IK_ITERATIONS"
echo "GRASP_RESET_IK_DAMPING=$GRASP_RESET_IK_DAMPING"
echo "GRASP_RESET_IK_MAX_JOINT_STEP=$GRASP_RESET_IK_MAX_JOINT_STEP"
echo "GRASP_RESET_IK_POS_TOLERANCE=$GRASP_RESET_IK_POS_TOLERANCE"
echo "GRASP_RESET_IK_ROT_TOLERANCE=$GRASP_RESET_IK_ROT_TOLERANCE"
echo "GRASP_PREGRASP_OFFSET=$GRASP_PREGRASP_OFFSET"
echo "GRASP_CONTACT_SCORE_STEPS=$GRASP_CONTACT_SCORE_STEPS"
echo "RUN_DIR_HOST=$RUN_DIR_HOST"
echo "METRICS_CONTAINER=$METRICS_CONTAINER"

srun \
  --ntasks=1 \
  --container-image="$IMAGE" \
  --container-mounts=/dev/shm:/dev/shm,"$CODE_NFS":/code,"$FABRICS_NFS":/fabrics,"$ISAACLAB_NFS":/IsaacLab,"$ENV_ROOT":/envs,"$RESULTS_NFS":/results,"$CACHE_NFS/kit":/isaac-sim/kit/cache,"$CACHE_NFS/ov":/root/.cache/ov,"$CACHE_NFS/pip":/root/.cache/pip,"$CACHE_NFS/glcache":/root/.cache/nvidia/GLCache,"$CACHE_NFS/computecache":/root/.nv/ComputeCache,"$CACHE_NFS/omni_logs":/root/.nvidia-omniverse/logs,"$CACHE_NFS/carb_logs":/isaac-sim/kit/logs/Kit/Isaac-Sim,"$CACHE_NFS/data":/root/.local/share/ov/data,"$CACHE_NFS/documents":/root/Documents \
  --no-container-entrypoint \
  --container-remap-root \
  --container-writable \
  --export=ALL,PYTHONUNBUFFERED=1,HYDRA_FULL_ERROR=1,PYTHONFAULTHANDLER=1,TORCH_SHOW_CPP_STACKTRACES=1,ACCEPT_EULA=Y,PRIVACY_CONSENT=Y \
  bash -lc '
    set -euo pipefail
    export SITE="/envs/$ENV_NAME/site"
    export PYTHONPATH="$SITE:/code:/fabrics/src"
    for d in /IsaacLab/source/*; do
      if [ -d "$d" ]; then
        export PYTHONPATH="$d:$PYTHONPATH"
      fi
    done
    export WANDB_MODE=offline
    mkdir -p "$RUN_DIR_CONTAINER" /results/logs

    cd /code
    echo "container_host=$(hostname)"
    echo "container_cuda_visible_devices=${CUDA_VISIBLE_DEVICES:-unset}"
    echo "CODE_COMMIT=${CODE_COMMIT:-unknown}"
    git rev-parse HEAD 2>/dev/null || true
    nvidia-smi || true

    cd /code/dextrah_lab/rl_games
    VIDEO_VALIDATE_ARGS=(
      validate_franka_multi_object_grasp_videos.py
      --headless
      --device cuda:0
      --task "$TASK"
      --num_envs "$NUM_ENVS"
      --seed "$SEED"
      --output_dir "$RUN_DIR_CONTAINER"
      --metrics_path "$METRICS_CONTAINER"
      --object_asset_manifest_path "$OBJECT_ASSET_MANIFEST_PATH"
      --max_objects "$MAX_OBJECTS"
      --object_asset_assignment "$OBJECT_ASSET_ASSIGNMENT"
      --object_spawn_center_offset_x "$OBJECT_SPAWN_CENTER_OFFSET_X"
      --object_spawn_center_offset_y "$OBJECT_SPAWN_CENTER_OFFSET_Y"
      --object_spawn_xy_randomization "$OBJECT_SPAWN_XY_RANDOMIZATION"
      --object_spawn_yaw_randomization_deg "$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
      --object_stable_pose_count "$OBJECT_STABLE_POSE_COUNT"
      --render_warmup_frames "$RENDER_WARMUP_FRAMES"
      --reset_cycles "$RESET_CYCLES"
      --settle_steps "$SETTLE_STEPS"
      --perturb_steps "$PERTURB_STEPS"
      --perturb_push_steps "$PERTURB_PUSH_STEPS"
      --perturb_linear_velocity "$PERTURB_LINEAR_VELOCITY"
      --perturb_lateral_velocity "$PERTURB_LATERAL_VELOCITY"
      --perturb_angular_velocity "$PERTURB_ANGULAR_VELOCITY"
      --grasp_steps "$GRASP_STEPS"
      --grasp_object_settle_steps "$GRASP_OBJECT_SETTLE_STEPS"
      --object_reset_settle_steps "$OBJECT_RESET_SETTLE_STEPS"
      --grasp_warmstart_close_width "$GRASP_WARMSTART_CLOSE_WIDTH"
      --grasp_warmstart_prior_close_width_margin "$GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
      --grasp_warmstart_min_close_width "$GRASP_WARMSTART_MIN_CLOSE_WIDTH"
      --grasp_warmstart_lift_action_z "$GRASP_WARMSTART_LIFT_ACTION_Z"
      --grasp_warmstart_approach_steps "$GRASP_WARMSTART_APPROACH_STEPS"
      --grasp_warmstart_close_steps "$GRASP_WARMSTART_CLOSE_STEPS"
      --grasp_warmstart_lift_steps "$GRASP_WARMSTART_LIFT_STEPS"
      --grasp_warmstart_gain "$GRASP_WARMSTART_GAIN"
      --grasp_warmstart_max_position_action "$GRASP_WARMSTART_MAX_POSITION_ACTION"
      --grasp_warmstart_close_max_ee_error "$GRASP_WARMSTART_CLOSE_MAX_EE_ERROR"
      --grasp_warmstart_lift_max_ee_error "$GRASP_WARMSTART_LIFT_MAX_EE_ERROR"
      --grasp_warmstart_lift_max_finger_center_dist "$GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
      --grasp_warmstart_lift_closed_width_margin "$GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
      --capture_interval "$CAPTURE_INTERVAL"
      --grasp_reset_attempts "$GRASP_RESET_ATTEMPTS"
      --grasp_reset_min_pregrasp_z "$GRASP_RESET_MIN_PREGRASP_Z"
      --grasp_reset_min_contact_height_above_center "$GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER"
      --grasp_reset_candidate_count "$GRASP_RESET_CANDIDATE_COUNT"
      --grasp_reset_max_center_distance_frac "$GRASP_RESET_MAX_CENTER_DISTANCE_FRAC"
      --grasp_reset_min_width "$GRASP_RESET_MIN_WIDTH"
      --grasp_contact_score_steps "$GRASP_CONTACT_SCORE_STEPS"
    )
    if [ -n "$GRASP_PRIOR_VERIFIED_INDICES_PATH" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_prior_verified_indices_path "$GRASP_PRIOR_VERIFIED_INDICES_PATH")
    fi
    if [ -n "$GRASP_RESET_IK_ITERATIONS" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_reset_ik_iterations "$GRASP_RESET_IK_ITERATIONS")
    fi
    if [ -n "$GRASP_RESET_IK_DAMPING" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_reset_ik_damping "$GRASP_RESET_IK_DAMPING")
    fi
    if [ -n "$GRASP_RESET_IK_MAX_JOINT_STEP" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_reset_ik_max_joint_step "$GRASP_RESET_IK_MAX_JOINT_STEP")
    fi
    if [ -n "$GRASP_RESET_IK_POS_TOLERANCE" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_reset_ik_pos_tolerance "$GRASP_RESET_IK_POS_TOLERANCE")
    fi
    if [ -n "$GRASP_RESET_IK_ROT_TOLERANCE" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_reset_ik_rot_tolerance "$GRASP_RESET_IK_ROT_TOLERANCE")
    fi
    case "$GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH" in
      False|false|0|no|No) VIDEO_VALIDATE_ARGS+=(--no-grasp_warmstart_use_prior_close_width) ;;
      *) VIDEO_VALIDATE_ARGS+=(--grasp_warmstart_use_prior_close_width) ;;
    esac
    case "$GRASP_WARMSTART_TRACK_ORIENTATION" in
      False|false|0|no|No) VIDEO_VALIDATE_ARGS+=(--no-grasp_warmstart_track_orientation) ;;
      *) VIDEO_VALIDATE_ARGS+=(--grasp_warmstart_track_orientation) ;;
    esac
    case "$GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY" in
      True|true|1|yes|Yes) VIDEO_VALIDATE_ARGS+=(--grasp_warmstart_require_current_lift_ready) ;;
      False|false|0|no|No) VIDEO_VALIDATE_ARGS+=(--no-grasp_warmstart_require_current_lift_ready) ;;
    esac
    case "$GRASP_RESET_REQUIRE_TOPDOWN" in
      False|false|0|no|No) VIDEO_VALIDATE_ARGS+=(--no-grasp_reset_require_topdown) ;;
      *) VIDEO_VALIDATE_ARGS+=(--grasp_reset_require_topdown) ;;
    esac
    if [ -n "$GRASP_PREGRASP_OFFSET" ]; then
      VIDEO_VALIDATE_ARGS+=(--grasp_pregrasp_offset "$GRASP_PREGRASP_OFFSET")
    fi
    case "$OBJECT_STABLE_POSE_ENABLED" in
      True|true|1|yes|Yes) VIDEO_VALIDATE_ARGS+=(--object_stable_pose_enabled) ;;
    esac
    if [ -n "$OBJECT_STABLE_POSE_CACHE_DIR" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_stable_pose_cache_dir "$OBJECT_STABLE_POSE_CACHE_DIR")
    fi
    if [ -n "$OBJECT_DENSITY" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_density "$OBJECT_DENSITY")
    fi
    if [ -n "$OBJECT_STATIC_FRICTION" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_static_friction "$OBJECT_STATIC_FRICTION")
    fi
    if [ -n "$OBJECT_DYNAMIC_FRICTION" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_dynamic_friction "$OBJECT_DYNAMIC_FRICTION")
    fi
    if [ -n "$OBJECT_CONTACT_OFFSET" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_contact_offset "$OBJECT_CONTACT_OFFSET")
    fi
    if [ -n "$OBJECT_REST_OFFSET" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_rest_offset "$OBJECT_REST_OFFSET")
    fi
    if [ -n "$OBJECT_SOLVER_POSITION_ITERATIONS" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_solver_position_iterations "$OBJECT_SOLVER_POSITION_ITERATIONS")
    fi
    if [ -n "$OBJECT_SOLVER_VELOCITY_ITERATIONS" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_solver_velocity_iterations "$OBJECT_SOLVER_VELOCITY_ITERATIONS")
    fi
    if [ -n "$OBJECT_LINEAR_DAMPING" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_linear_damping "$OBJECT_LINEAR_DAMPING")
    fi
    if [ -n "$OBJECT_ANGULAR_DAMPING" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_angular_damping "$OBJECT_ANGULAR_DAMPING")
    fi
    if [ -n "$OBJECT_MAX_DEPENETRATION_VELOCITY" ]; then
      VIDEO_VALIDATE_ARGS+=(--object_max_depenetration_velocity "$OBJECT_MAX_DEPENETRATION_VELOCITY")
    fi
    case "$OBJECT_STABLE_POSE_RANDOMIZE" in
      False|false|0|no|No) VIDEO_VALIDATE_ARGS+=(--no-object_stable_pose_randomize) ;;
    esac
    case "$OBJECT_STABLE_POSE_ALLOW_MISSING" in
      True|true|1|yes|Yes) VIDEO_VALIDATE_ARGS+=(--object_stable_pose_allow_missing) ;;
    esac

    printf "video_validate_command="
    printf "%q " /isaac-sim/python.sh "${VIDEO_VALIDATE_ARGS[@]}"
    printf "\n"
    /isaac-sim/python.sh "${VIDEO_VALIDATE_ARGS[@]}"
  '

if [ -f "$LOG_FILE" ] && grep -E "Traceback|RuntimeError:|Error executing job with overrides|ChildFailedError|Could not execute <function load" "$LOG_FILE" >/dev/null; then
  echo "Detected video validation error patterns in $LOG_FILE."
  exit 1
fi

if [ ! -s "$RUN_DIR_HOST/video_metrics.json" ]; then
  echo "Missing video metrics JSON: $RUN_DIR_HOST/video_metrics.json"
  exit 1
fi

python3 - "$RUN_DIR_HOST/video_metrics.json" <<'PY'
import json
import sys

metrics_path = sys.argv[1]
with open(metrics_path, "r", encoding="utf-8") as f:
    payload = json.load(f)
if not bool(payload.get("passed", False)):
    failed = [name for name, item in payload.get("scenarios", {}).items() if not bool(item.get("passed", False))]
    print(f"Video validation metrics failed: {failed}")
    sys.exit(1)
print("Video validation metrics passed")
PY

echo "Video Validation Done"
