#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --account=nvr_lpr_rvp
#SBATCH --gpus-per-node=1
#SBATCH --job-name=dextrah_multi_verify
#SBATCH --partition=batch
#SBATCH --time=0-02:00:00
#SBATCH --mem=128G
#SBATCH --cpus-per-task=16
#SBATCH --output=/lustre/fsw/portfolios/nvr/users/lzha/slurm_logs/dextrah/collect_franka_multi_object_verified_grasps_%j.out

set -euo pipefail

NFS_ROOT="${NFS_ROOT:-/lustre/fsw/portfolios/nvr/users/lzha}"
CODE_NFS="${CODE_NFS:-$NFS_ROOT/src/DEXTRAH}"
FABRICS_NFS="${FABRICS_NFS:-$NFS_ROOT/src/FABRICS}"
ISAACLAB_NFS="${ISAACLAB_NFS:-$NFS_ROOT/src/IsaacLab-v2.2.1}"
IMAGE="${IMAGE:-$NFS_ROOT/cache/isaac_lab_2.2.0.sqsh}"
ENV_ROOT="${ENV_ROOT:-$NFS_ROOT/envs}"
ENV_NAME="${ENV_NAME:-dextrah-isaaclab}"
RESULTS_NFS="${RESULTS_NFS:-$NFS_ROOT/results/dextrah}"
CACHE_NFS="${CACHE_NFS:-$NFS_ROOT/isaac_cache}"

TASK="${TASK:-Dextrah-Franka-Multi-Object-Grasp}"
SLURM_JOB_ID_SAFE="${SLURM_JOB_ID:-manual}"
RUN_NAME="${RUN_NAME:-franka_multi_verified_grasps_${SLURM_JOB_ID_SAFE}_$(date +%Y%m%d_%H%M%S)}"
NUM_ENVS="${NUM_ENVS:-64}"
SEED="${SEED:-42}"
OBJECT_ASSET_MANIFEST_PATH="${OBJECT_ASSET_MANIFEST_PATH:-}"
MAX_OBJECTS="${MAX_OBJECTS:-2}"
OBJECT_ASSET_ASSIGNMENT="${OBJECT_ASSET_ASSIGNMENT:-round_robin}"
OBJECT_SPAWN_CENTER_OFFSET_X="${OBJECT_SPAWN_CENTER_OFFSET_X:-0.05}"
OBJECT_SPAWN_CENTER_OFFSET_Y="${OBJECT_SPAWN_CENTER_OFFSET_Y:-0.0}"
OBJECT_SPAWN_XY_RANDOMIZATION="${OBJECT_SPAWN_XY_RANDOMIZATION:-0.10}"
OBJECT_SPAWN_YAW_RANDOMIZATION_DEG="${OBJECT_SPAWN_YAW_RANDOMIZATION_DEG:-180.0}"
OBJECT_STABLE_POSE_ENABLED="${OBJECT_STABLE_POSE_ENABLED:-False}"
OBJECT_STABLE_POSE_CACHE_DIR="${OBJECT_STABLE_POSE_CACHE_DIR:-}"
OBJECT_STABLE_POSE_COUNT="${OBJECT_STABLE_POSE_COUNT:-1}"
OBJECT_STABLE_POSE_RANDOMIZE="${OBJECT_STABLE_POSE_RANDOMIZE:-True}"
OBJECT_STABLE_POSE_ALLOW_MISSING="${OBJECT_STABLE_POSE_ALLOW_MISSING:-False}"
CYCLES="${CYCLES:-120}"
MIN_CYCLES="${MIN_CYCLES:-10}"
TARGET_PER_OBJECT="${TARGET_PER_OBJECT:-8}"
MIN_PASS_OBSERVATIONS_PER_INDEX="${MIN_PASS_OBSERVATIONS_PER_INDEX:-1}"
MIN_PASS_RATE_PER_INDEX="${MIN_PASS_RATE_PER_INDEX:-0.0}"
MAX_INDICES_PER_OBJECT="${MAX_INDICES_PER_OBJECT:-128}"
SCORE_STEPS="${SCORE_STEPS:-220}"
MIN_LIFT_HEIGHT="${MIN_LIFT_HEIGHT:-0.10}"
MAX_XY_DELTA="${MAX_XY_DELTA:-0.15}"
MAX_FINGER_DIST="${MAX_FINGER_DIST:-0.25}"
MAX_DONE_COUNT="${MAX_DONE_COUNT:-0}"
REQUIRE_SUCCESS="${REQUIRE_SUCCESS:-False}"
GRASP_RESET_ATTEMPTS="${GRASP_RESET_ATTEMPTS:-4}"
GRASP_RESET_REQUIRE_TOPDOWN="${GRASP_RESET_REQUIRE_TOPDOWN:-True}"
GRASP_RESET_MIN_PREGRASP_Z="${GRASP_RESET_MIN_PREGRASP_Z:-0.45}"
GRASP_RESET_REQUIRE_DOWNWARD_TOOL_Z="${GRASP_RESET_REQUIRE_DOWNWARD_TOOL_Z:-True}"
GRASP_RESET_MIN_DOWNWARD_TOOL_Z="${GRASP_RESET_MIN_DOWNWARD_TOOL_Z:-0.45}"
GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER="${GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER:-0.0}"
GRASP_RESET_CANDIDATE_COUNT="${GRASP_RESET_CANDIDATE_COUNT:-2048}"
GRASP_RESET_MAX_CENTER_DISTANCE_FRAC="${GRASP_RESET_MAX_CENTER_DISTANCE_FRAC:-0.35}"
GRASP_RESET_MIN_WIDTH="${GRASP_RESET_MIN_WIDTH:-0.008}"
GRASP_RESET_IK_ITERATIONS="${GRASP_RESET_IK_ITERATIONS:-96}"
GRASP_RESET_IK_DAMPING="${GRASP_RESET_IK_DAMPING:-0.035}"
GRASP_RESET_IK_MAX_JOINT_STEP="${GRASP_RESET_IK_MAX_JOINT_STEP:-0.25}"
GRASP_RESET_IK_POS_TOLERANCE="${GRASP_RESET_IK_POS_TOLERANCE:-0.055}"
GRASP_RESET_IK_ROT_TOLERANCE="${GRASP_RESET_IK_ROT_TOLERANCE:-0.55}"
GRASP_PREGRASP_OFFSET="${GRASP_PREGRASP_OFFSET:-0.08}"
GRASP_WARMSTART_CLOSE_WIDTH="${GRASP_WARMSTART_CLOSE_WIDTH:-0.0}"
GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH="${GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH:-False}"
GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN="${GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN:-0.003}"
GRASP_WARMSTART_MIN_CLOSE_WIDTH="${GRASP_WARMSTART_MIN_CLOSE_WIDTH:-0.0}"
GRASP_WARMSTART_LIFT_ACTION_Z="${GRASP_WARMSTART_LIFT_ACTION_Z:-1.0}"
GRASP_WARMSTART_APPROACH_STEPS="${GRASP_WARMSTART_APPROACH_STEPS:-20}"
GRASP_WARMSTART_CLOSE_STEPS="${GRASP_WARMSTART_CLOSE_STEPS:-28}"
GRASP_WARMSTART_LIFT_STEPS="${GRASP_WARMSTART_LIFT_STEPS:-80}"
GRASP_WARMSTART_GAIN="${GRASP_WARMSTART_GAIN:-8.0}"
GRASP_WARMSTART_MAX_POSITION_ACTION="${GRASP_WARMSTART_MAX_POSITION_ACTION:-1.0}"
GRASP_WARMSTART_TRACK_ORIENTATION="${GRASP_WARMSTART_TRACK_ORIENTATION:-True}"
GRASP_WARMSTART_CLOSE_MAX_EE_ERROR="${GRASP_WARMSTART_CLOSE_MAX_EE_ERROR:-0.0}"
GRASP_WARMSTART_LIFT_MAX_EE_ERROR="${GRASP_WARMSTART_LIFT_MAX_EE_ERROR:-0.0}"
GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST="${GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST:-0.0}"
GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN="${GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN:--1.0}"
GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY="${GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY:-}"
CODE_COMMIT="${CODE_COMMIT:-}"
if [ -z "$CODE_COMMIT" ] && git -C "$CODE_NFS" rev-parse HEAD >/dev/null 2>&1; then
  CODE_COMMIT="$(git -C "$CODE_NFS" rev-parse HEAD)"
fi

RUN_DIR_HOST="$RESULTS_NFS/assets/verified_grasp_indices/$RUN_NAME"
RUN_DIR_CONTAINER="/results/assets/verified_grasp_indices/$RUN_NAME"
OUTPUT_HOST="$RUN_DIR_HOST/verified_indices.json"
OUTPUT_CONTAINER="$RUN_DIR_CONTAINER/verified_indices.json"
LOG_FILE="$NFS_ROOT/slurm_logs/dextrah/collect_franka_multi_object_verified_grasps_${SLURM_JOB_ID_SAFE}.out"

if [ -z "$OBJECT_ASSET_MANIFEST_PATH" ]; then
  echo "OBJECT_ASSET_MANIFEST_PATH is required"
  exit 2
fi
if [ ! -f "$IMAGE" ]; then
  echo "Missing Isaac Lab container image: $IMAGE"
  exit 2
fi
if [ ! -d "$ENV_ROOT/$ENV_NAME/site" ]; then
  echo "Missing DEXTRAH Python target: $ENV_ROOT/$ENV_NAME/site"
  exit 2
fi

mkdir -p \
  "$RUN_DIR_HOST" \
  "$NFS_ROOT/slurm_logs/dextrah" \
  "$CACHE_NFS/kit" "$CACHE_NFS/ov" "$CACHE_NFS/pip" \
  "$CACHE_NFS/glcache" "$CACHE_NFS/computecache" \
  "$CACHE_NFS/omni_logs" "$CACHE_NFS/carb_logs" \
  "$CACHE_NFS/data" "$CACHE_NFS/documents"

export TASK RUN_NAME NUM_ENVS SEED OBJECT_ASSET_MANIFEST_PATH MAX_OBJECTS OBJECT_ASSET_ASSIGNMENT
export OBJECT_SPAWN_CENTER_OFFSET_X OBJECT_SPAWN_CENTER_OFFSET_Y OBJECT_SPAWN_XY_RANDOMIZATION
export OBJECT_SPAWN_YAW_RANDOMIZATION_DEG OBJECT_STABLE_POSE_ENABLED OBJECT_STABLE_POSE_CACHE_DIR
export OBJECT_STABLE_POSE_COUNT OBJECT_STABLE_POSE_RANDOMIZE OBJECT_STABLE_POSE_ALLOW_MISSING
export CYCLES MIN_CYCLES TARGET_PER_OBJECT MIN_PASS_OBSERVATIONS_PER_INDEX MIN_PASS_RATE_PER_INDEX
export MAX_INDICES_PER_OBJECT SCORE_STEPS
export MIN_LIFT_HEIGHT MAX_XY_DELTA MAX_FINGER_DIST MAX_DONE_COUNT REQUIRE_SUCCESS
export GRASP_RESET_ATTEMPTS GRASP_RESET_REQUIRE_TOPDOWN GRASP_RESET_MIN_PREGRASP_Z
export GRASP_RESET_REQUIRE_DOWNWARD_TOOL_Z GRASP_RESET_MIN_DOWNWARD_TOOL_Z
export GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER
export GRASP_RESET_CANDIDATE_COUNT GRASP_RESET_MAX_CENTER_DISTANCE_FRAC GRASP_RESET_MIN_WIDTH
export GRASP_RESET_IK_ITERATIONS GRASP_RESET_IK_DAMPING GRASP_RESET_IK_MAX_JOINT_STEP
export GRASP_RESET_IK_POS_TOLERANCE GRASP_RESET_IK_ROT_TOLERANCE GRASP_PREGRASP_OFFSET
export GRASP_WARMSTART_CLOSE_WIDTH GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH
export GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN GRASP_WARMSTART_MIN_CLOSE_WIDTH
export GRASP_WARMSTART_LIFT_ACTION_Z GRASP_WARMSTART_APPROACH_STEPS GRASP_WARMSTART_CLOSE_STEPS
export GRASP_WARMSTART_LIFT_STEPS GRASP_WARMSTART_GAIN GRASP_WARMSTART_MAX_POSITION_ACTION
export GRASP_WARMSTART_TRACK_ORIENTATION GRASP_WARMSTART_CLOSE_MAX_EE_ERROR
export GRASP_WARMSTART_LIFT_MAX_EE_ERROR GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST
export GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY
export RUN_DIR_CONTAINER OUTPUT_CONTAINER ENV_NAME CODE_COMMIT

echo "Running DextrAH Franka multi-object verified-grasp collection"
echo "SLURM_JOB_ID=$SLURM_JOB_ID_SAFE"
echo "SLURM_JOB_NODELIST=${SLURM_JOB_NODELIST:-unset}"
echo "IMAGE=$IMAGE"
echo "CODE_NFS=$CODE_NFS"
echo "FABRICS_NFS=$FABRICS_NFS"
echo "ISAACLAB_NFS=$ISAACLAB_NFS"
echo "CODE_COMMIT=${CODE_COMMIT:-unknown}"
echo "RESULTS_NFS=$RESULTS_NFS"
echo "TASK=$TASK"
echo "RUN_NAME=$RUN_NAME"
echo "NUM_ENVS=$NUM_ENVS"
echo "SEED=$SEED"
echo "OBJECT_ASSET_MANIFEST_PATH=$OBJECT_ASSET_MANIFEST_PATH"
echo "MAX_OBJECTS=$MAX_OBJECTS"
echo "OBJECT_ASSET_ASSIGNMENT=$OBJECT_ASSET_ASSIGNMENT"
echo "OBJECT_SPAWN_CENTER_OFFSET_X=$OBJECT_SPAWN_CENTER_OFFSET_X"
echo "OBJECT_SPAWN_CENTER_OFFSET_Y=$OBJECT_SPAWN_CENTER_OFFSET_Y"
echo "OBJECT_SPAWN_XY_RANDOMIZATION=$OBJECT_SPAWN_XY_RANDOMIZATION"
echo "OBJECT_SPAWN_YAW_RANDOMIZATION_DEG=$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
echo "OBJECT_STABLE_POSE_ENABLED=$OBJECT_STABLE_POSE_ENABLED"
echo "OBJECT_STABLE_POSE_CACHE_DIR=$OBJECT_STABLE_POSE_CACHE_DIR"
echo "OBJECT_STABLE_POSE_COUNT=$OBJECT_STABLE_POSE_COUNT"
echo "OBJECT_STABLE_POSE_RANDOMIZE=$OBJECT_STABLE_POSE_RANDOMIZE"
echo "OBJECT_STABLE_POSE_ALLOW_MISSING=$OBJECT_STABLE_POSE_ALLOW_MISSING"
echo "CYCLES=$CYCLES"
echo "MIN_CYCLES=$MIN_CYCLES"
echo "TARGET_PER_OBJECT=$TARGET_PER_OBJECT"
echo "MIN_PASS_OBSERVATIONS_PER_INDEX=$MIN_PASS_OBSERVATIONS_PER_INDEX"
echo "MIN_PASS_RATE_PER_INDEX=$MIN_PASS_RATE_PER_INDEX"
echo "MAX_INDICES_PER_OBJECT=$MAX_INDICES_PER_OBJECT"
echo "SCORE_STEPS=$SCORE_STEPS"
echo "MIN_LIFT_HEIGHT=$MIN_LIFT_HEIGHT"
echo "MAX_XY_DELTA=$MAX_XY_DELTA"
echo "MAX_FINGER_DIST=$MAX_FINGER_DIST"
echo "MAX_DONE_COUNT=$MAX_DONE_COUNT"
echo "REQUIRE_SUCCESS=$REQUIRE_SUCCESS"
echo "GRASP_RESET_ATTEMPTS=$GRASP_RESET_ATTEMPTS"
echo "GRASP_RESET_REQUIRE_TOPDOWN=$GRASP_RESET_REQUIRE_TOPDOWN"
echo "GRASP_RESET_MIN_PREGRASP_Z=$GRASP_RESET_MIN_PREGRASP_Z"
echo "GRASP_RESET_REQUIRE_DOWNWARD_TOOL_Z=$GRASP_RESET_REQUIRE_DOWNWARD_TOOL_Z"
echo "GRASP_RESET_MIN_DOWNWARD_TOOL_Z=$GRASP_RESET_MIN_DOWNWARD_TOOL_Z"
echo "GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER=$GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER"
echo "GRASP_RESET_CANDIDATE_COUNT=$GRASP_RESET_CANDIDATE_COUNT"
echo "GRASP_RESET_MAX_CENTER_DISTANCE_FRAC=$GRASP_RESET_MAX_CENTER_DISTANCE_FRAC"
echo "GRASP_RESET_MIN_WIDTH=$GRASP_RESET_MIN_WIDTH"
echo "GRASP_RESET_IK_ITERATIONS=$GRASP_RESET_IK_ITERATIONS"
echo "GRASP_RESET_IK_DAMPING=$GRASP_RESET_IK_DAMPING"
echo "GRASP_RESET_IK_MAX_JOINT_STEP=$GRASP_RESET_IK_MAX_JOINT_STEP"
echo "GRASP_RESET_IK_POS_TOLERANCE=$GRASP_RESET_IK_POS_TOLERANCE"
echo "GRASP_RESET_IK_ROT_TOLERANCE=$GRASP_RESET_IK_ROT_TOLERANCE"
echo "GRASP_PREGRASP_OFFSET=$GRASP_PREGRASP_OFFSET"
echo "GRASP_WARMSTART_CLOSE_WIDTH=$GRASP_WARMSTART_CLOSE_WIDTH"
echo "GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH=$GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH"
echo "GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN=$GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
echo "GRASP_WARMSTART_MIN_CLOSE_WIDTH=$GRASP_WARMSTART_MIN_CLOSE_WIDTH"
echo "GRASP_WARMSTART_LIFT_ACTION_Z=$GRASP_WARMSTART_LIFT_ACTION_Z"
echo "GRASP_WARMSTART_APPROACH_STEPS=$GRASP_WARMSTART_APPROACH_STEPS"
echo "GRASP_WARMSTART_CLOSE_STEPS=$GRASP_WARMSTART_CLOSE_STEPS"
echo "GRASP_WARMSTART_LIFT_STEPS=$GRASP_WARMSTART_LIFT_STEPS"
echo "GRASP_WARMSTART_GAIN=$GRASP_WARMSTART_GAIN"
echo "GRASP_WARMSTART_MAX_POSITION_ACTION=$GRASP_WARMSTART_MAX_POSITION_ACTION"
echo "GRASP_WARMSTART_TRACK_ORIENTATION=$GRASP_WARMSTART_TRACK_ORIENTATION"
echo "GRASP_WARMSTART_CLOSE_MAX_EE_ERROR=$GRASP_WARMSTART_CLOSE_MAX_EE_ERROR"
echo "GRASP_WARMSTART_LIFT_MAX_EE_ERROR=$GRASP_WARMSTART_LIFT_MAX_EE_ERROR"
echo "GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST=$GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
echo "GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN=$GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
echo "GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY=$GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY"
echo "RUN_DIR_HOST=$RUN_DIR_HOST"
echo "OUTPUT_HOST=$OUTPUT_HOST"

srun \
  --ntasks=1 \
  --container-image="$IMAGE" \
  --container-mounts=/dev/shm:/dev/shm,"$CODE_NFS":/code,"$FABRICS_NFS":/fabrics,"$ISAACLAB_NFS":/IsaacLab,"$ENV_ROOT":/envs,"$RESULTS_NFS":/results,"$CACHE_NFS/kit":/isaac-sim/kit/cache,"$CACHE_NFS/ov":/root/.cache/ov,"$CACHE_NFS/pip":/root/.cache/pip,"$CACHE_NFS/glcache":/root/.cache/nvidia/GLCache,"$CACHE_NFS/computecache":/root/.nv/ComputeCache,"$CACHE_NFS/omni_logs":/root/.nvidia-omniverse/logs,"$CACHE_NFS/carb_logs":/isaac-sim/kit/logs/Kit/Isaac-Sim,"$CACHE_NFS/data":/root/.local/share/ov/data,"$CACHE_NFS/documents":/root/Documents \
  --no-container-entrypoint \
  --container-remap-root \
  --container-writable \
  --export=ALL,PYTHONUNBUFFERED=1,HYDRA_FULL_ERROR=1,PYTHONFAULTHANDLER=1,TORCH_SHOW_CPP_STACKTRACES=1,ACCEPT_EULA=Y,PRIVACY_CONSENT=Y \
  bash -lc '
    set -euxo pipefail
    export SITE="/envs/$ENV_NAME/site"
    export PYTHONPATH="$SITE:/code:/fabrics/src"
    for d in /IsaacLab/source/*; do
      if [ -d "$d" ]; then
        export PYTHONPATH="$d:$PYTHONPATH"
      fi
    done
    export WANDB_MODE=offline
    mkdir -p "$RUN_DIR_CONTAINER" /results/logs

    cd /code
    echo "container_host=$(hostname)"
    echo "container_cuda_visible_devices=${CUDA_VISIBLE_DEVICES:-unset}"
    echo "CODE_COMMIT=${CODE_COMMIT:-unknown}"
    git rev-parse HEAD 2>/dev/null || true
    git status --short 2>/dev/null || true
    nvidia-smi || true

    cd /code/dextrah_lab/rl_games
    COLLECT_ARGS=(
      collect_franka_multi_object_verified_grasps.py
      --headless
      --device cuda:0
      --task "$TASK"
      --num_envs "$NUM_ENVS"
      --seed "$SEED"
      --output_path "$OUTPUT_CONTAINER"
      --object_asset_manifest_path "$OBJECT_ASSET_MANIFEST_PATH"
      --max_objects "$MAX_OBJECTS"
      --object_asset_assignment "$OBJECT_ASSET_ASSIGNMENT"
      --object_spawn_center_offset_x "$OBJECT_SPAWN_CENTER_OFFSET_X"
      --object_spawn_center_offset_y "$OBJECT_SPAWN_CENTER_OFFSET_Y"
      --object_spawn_xy_randomization "$OBJECT_SPAWN_XY_RANDOMIZATION"
      --object_spawn_yaw_randomization_deg "$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
      --object_stable_pose_count "$OBJECT_STABLE_POSE_COUNT"
      --cycles "$CYCLES"
      --min_cycles "$MIN_CYCLES"
      --target_per_object "$TARGET_PER_OBJECT"
      --min_pass_observations_per_index "$MIN_PASS_OBSERVATIONS_PER_INDEX"
      --min_pass_rate_per_index "$MIN_PASS_RATE_PER_INDEX"
      --max_indices_per_object "$MAX_INDICES_PER_OBJECT"
      --score_steps "$SCORE_STEPS"
      --min_lift_height "$MIN_LIFT_HEIGHT"
      --max_xy_delta "$MAX_XY_DELTA"
      --max_finger_dist "$MAX_FINGER_DIST"
      --max_done_count "$MAX_DONE_COUNT"
      --grasp_reset_attempts "$GRASP_RESET_ATTEMPTS"
      --grasp_reset_min_pregrasp_z "$GRASP_RESET_MIN_PREGRASP_Z"
      --grasp_reset_min_downward_tool_z "$GRASP_RESET_MIN_DOWNWARD_TOOL_Z"
      --grasp_reset_min_contact_height_above_center "$GRASP_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER"
      --grasp_reset_candidate_count "$GRASP_RESET_CANDIDATE_COUNT"
      --grasp_reset_max_center_distance_frac "$GRASP_RESET_MAX_CENTER_DISTANCE_FRAC"
      --grasp_reset_min_width "$GRASP_RESET_MIN_WIDTH"
      --grasp_reset_ik_iterations "$GRASP_RESET_IK_ITERATIONS"
      --grasp_reset_ik_damping "$GRASP_RESET_IK_DAMPING"
      --grasp_reset_ik_max_joint_step "$GRASP_RESET_IK_MAX_JOINT_STEP"
      --grasp_reset_ik_pos_tolerance "$GRASP_RESET_IK_POS_TOLERANCE"
      --grasp_reset_ik_rot_tolerance "$GRASP_RESET_IK_ROT_TOLERANCE"
      --grasp_pregrasp_offset "$GRASP_PREGRASP_OFFSET"
      --grasp_warmstart_close_width "$GRASP_WARMSTART_CLOSE_WIDTH"
      --grasp_warmstart_prior_close_width_margin "$GRASP_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
      --grasp_warmstart_min_close_width "$GRASP_WARMSTART_MIN_CLOSE_WIDTH"
      --grasp_warmstart_lift_action_z "$GRASP_WARMSTART_LIFT_ACTION_Z"
      --grasp_warmstart_approach_steps "$GRASP_WARMSTART_APPROACH_STEPS"
      --grasp_warmstart_close_steps "$GRASP_WARMSTART_CLOSE_STEPS"
      --grasp_warmstart_lift_steps "$GRASP_WARMSTART_LIFT_STEPS"
      --grasp_warmstart_gain "$GRASP_WARMSTART_GAIN"
      --grasp_warmstart_max_position_action "$GRASP_WARMSTART_MAX_POSITION_ACTION"
      --grasp_warmstart_close_max_ee_error "$GRASP_WARMSTART_CLOSE_MAX_EE_ERROR"
      --grasp_warmstart_lift_max_ee_error "$GRASP_WARMSTART_LIFT_MAX_EE_ERROR"
      --grasp_warmstart_lift_max_finger_center_dist "$GRASP_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
      --grasp_warmstart_lift_closed_width_margin "$GRASP_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
    )
    case "$GRASP_WARMSTART_REQUIRE_CURRENT_LIFT_READY" in
      True|true|1|yes|Yes) COLLECT_ARGS+=(--grasp_warmstart_require_current_lift_ready) ;;
      False|false|0|no|No) COLLECT_ARGS+=(--no-grasp_warmstart_require_current_lift_ready) ;;
    esac
    case "$OBJECT_STABLE_POSE_ENABLED" in
      True|true|1|yes|Yes) COLLECT_ARGS+=(--object_stable_pose_enabled) ;;
    esac
    if [ -n "$OBJECT_STABLE_POSE_CACHE_DIR" ]; then
      COLLECT_ARGS+=(--object_stable_pose_cache_dir "$OBJECT_STABLE_POSE_CACHE_DIR")
    fi
    case "$OBJECT_STABLE_POSE_RANDOMIZE" in
      False|false|0|no|No) COLLECT_ARGS+=(--no-object_stable_pose_randomize) ;;
    esac
    case "$OBJECT_STABLE_POSE_ALLOW_MISSING" in
      True|true|1|yes|Yes) COLLECT_ARGS+=(--object_stable_pose_allow_missing) ;;
    esac
    case "$GRASP_WARMSTART_USE_PRIOR_CLOSE_WIDTH" in
      True|true|1|yes|Yes) COLLECT_ARGS+=(--grasp_warmstart_use_prior_close_width) ;;
      *) COLLECT_ARGS+=(--no-grasp_warmstart_use_prior_close_width) ;;
    esac
    case "$GRASP_WARMSTART_TRACK_ORIENTATION" in
      False|false|0|no|No) COLLECT_ARGS+=(--no-grasp_warmstart_track_orientation) ;;
      *) COLLECT_ARGS+=(--grasp_warmstart_track_orientation) ;;
    esac
    case "$GRASP_RESET_REQUIRE_TOPDOWN" in
      False|false|0|no|No) COLLECT_ARGS+=(--no-grasp_reset_require_topdown) ;;
      *) COLLECT_ARGS+=(--grasp_reset_require_topdown) ;;
    esac
    case "$GRASP_RESET_REQUIRE_DOWNWARD_TOOL_Z" in
      False|false|0|no|No) COLLECT_ARGS+=(--no-grasp_reset_require_downward_tool_z) ;;
      *) COLLECT_ARGS+=(--grasp_reset_require_downward_tool_z) ;;
    esac
    case "$REQUIRE_SUCCESS" in
      True|true|1|yes|Yes) COLLECT_ARGS+=(--require_success) ;;
    esac

    printf "collect_verified_grasps_command="
    printf "%q " /isaac-sim/python.sh "${COLLECT_ARGS[@]}"
    printf "\n"
    /isaac-sim/python.sh "${COLLECT_ARGS[@]}"
  '

if [ -f "$LOG_FILE" ] && grep -E "Traceback|RuntimeError:|Error executing job with overrides|ChildFailedError|Could not execute <function load" "$LOG_FILE" >/dev/null; then
  echo "Detected verified-grasp collection error patterns in $LOG_FILE."
  exit 1
fi

if [ ! -s "$OUTPUT_HOST" ]; then
  echo "Missing verified grasp JSON: $OUTPUT_HOST"
  exit 1
fi

python3 - "$OUTPUT_HOST" "$TARGET_PER_OBJECT" <<'PY'
import json
import sys

path = sys.argv[1]
target = int(sys.argv[2])
with open(path, "r", encoding="utf-8") as f:
    payload = json.load(f)
counts = payload.get("summary", {}).get("counts_by_uuid", {})
missing = {uuid: int(count) for uuid, count in counts.items() if int(count) < target}
print(f"verified grasp counts: {counts}")
if missing:
    print(f"Missing target counts: {missing}")
    sys.exit(1)
PY

echo "Verified Grasp Collection Done: $OUTPUT_HOST"
