#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --account=nvr_lpr_rvp
#SBATCH --gpus-per-node=8
#SBATCH --job-name=dextrah_teacher_8gpu
#SBATCH --partition=batch_singlenode,grizzly,polar,polar3,polar4,interactive_singlenode
#SBATCH --time=0-03:50:00
#SBATCH --mem=0
#SBATCH --cpus-per-task=64
#SBATCH --output=/lustre/fsw/portfolios/nvr/users/lzha/slurm_logs/dextrah/teacher_8gpu_%j.out
#SBATCH --signal=B:TERM@300

set -euo pipefail

NFS_ROOT="${NFS_ROOT:-/lustre/fsw/portfolios/nvr/users/lzha}"
CODE_NFS="${CODE_NFS:-$NFS_ROOT/src/DEXTRAH}"
FABRICS_NFS="${FABRICS_NFS:-$NFS_ROOT/src/FABRICS}"
ISAACLAB_NFS="${ISAACLAB_NFS:-$NFS_ROOT/src/IsaacLab-v2.2.1}"
IMAGE="${IMAGE:-$NFS_ROOT/cache/isaac_lab_2.2.0.sqsh}"
ENV_ROOT="${ENV_ROOT:-$NFS_ROOT/envs}"
ENV_NAME="${ENV_NAME:-dextrah-isaaclab}"
RESULTS_NFS="${RESULTS_NFS:-$NFS_ROOT/results/dextrah}"
CACHE_NFS="${CACHE_NFS:-$NFS_ROOT/isaac_cache}"

NPROC_PER_NODE="${NPROC_PER_NODE:-8}"
NUM_NODES="${NUM_NODES:-1}"
TASK="${TASK:-Dextrah-Kuka-Allegro}"
USE_CUDA_GRAPH="${USE_CUDA_GRAPH:-}"
SLURM_JOB_ID_SAFE="${SLURM_JOB_ID:-0}"
JOB_ID_SUFFIX="${SLURM_JOB_ID_SAFE: -4}"
MASTER_PORT="${MASTER_PORT:-$((10000 + 10#$JOB_ID_SUFFIX))}"
MAX_ITERATIONS="${MAX_ITERATIONS:-}"
SEED="${SEED:--1}"
DISTRIBUTED="${DISTRIBUTED:-True}"
MULTI_GPU="${MULTI_GPU:-True}"
if [ "$TASK" = "Dextrah-Cube-Grasp" ]; then
  NUM_ENVS="${NUM_ENVS:-4096}"
  MINIBATCH_SIZE="${MINIBATCH_SIZE:-32768}"
  CENTRAL_VALUE_MINIBATCH_SIZE="${CENTRAL_VALUE_MINIBATCH_SIZE:-32768}"
  LEARNING_RATE="${LEARNING_RATE:-0.0002}"
  CENTRAL_VALUE_LEARNING_RATE="${CENTRAL_VALUE_LEARNING_RATE:-0.0001}"
  HORIZON_LENGTH="${HORIZON_LENGTH:-32}"
  MINI_EPOCHS="${MINI_EPOCHS:-4}"
  SAVE_FREQUENCY="${SAVE_FREQUENCY:-25}"
  GAMMA="${GAMMA:-0.995}"
  TAU="${TAU:-0.95}"
  KL_THRESHOLD="${KL_THRESHOLD:-0.012}"
  ENTROPY_COEF="${ENTROPY_COEF:-0.0005}"
  E_CLIP="${E_CLIP:-0.2}"
  GRAD_NORM="${GRAD_NORM:-1.0}"
elif [ "$TASK" = "Dextrah-Franka-Star-Kitting" ]; then
  NUM_ENVS="${NUM_ENVS:-2048}"
  MINIBATCH_SIZE="${MINIBATCH_SIZE:-32768}"
  CENTRAL_VALUE_MINIBATCH_SIZE="${CENTRAL_VALUE_MINIBATCH_SIZE:-32768}"
  LEARNING_RATE="${LEARNING_RATE:-0.00015}"
  CENTRAL_VALUE_LEARNING_RATE="${CENTRAL_VALUE_LEARNING_RATE:-0.0001}"
  HORIZON_LENGTH="${HORIZON_LENGTH:-48}"
  MINI_EPOCHS="${MINI_EPOCHS:-4}"
  SAVE_FREQUENCY="${SAVE_FREQUENCY:-25}"
  GAMMA="${GAMMA:-0.997}"
  TAU="${TAU:-0.95}"
  KL_THRESHOLD="${KL_THRESHOLD:-0.012}"
  ENTROPY_COEF="${ENTROPY_COEF:-0.001}"
  E_CLIP="${E_CLIP:-0.2}"
  GRAD_NORM="${GRAD_NORM:-1.0}"
elif [ "$TASK" = "Dextrah-Franka-Cube-Grasp" ] \
  || [ "$TASK" = "Dextrah-Franka-Cube-Grasp-Traj-Tracking" ] \
  || [ "$TASK" = "Dextrah-Franka-Multi-Object-Grasp" ] \
  || [ "$TASK" = "Dextrah-Franka-Tabletop-Clutter-Grasp" ]; then
  NUM_ENVS="${NUM_ENVS:-2048}"
  MINIBATCH_SIZE="${MINIBATCH_SIZE:-32768}"
  CENTRAL_VALUE_MINIBATCH_SIZE="${CENTRAL_VALUE_MINIBATCH_SIZE:-32768}"
  LEARNING_RATE="${LEARNING_RATE:-0.0002}"
  CENTRAL_VALUE_LEARNING_RATE="${CENTRAL_VALUE_LEARNING_RATE:-0.0001}"
  HORIZON_LENGTH="${HORIZON_LENGTH:-64}"
  MINI_EPOCHS="${MINI_EPOCHS:-4}"
  SAVE_FREQUENCY="${SAVE_FREQUENCY:-25}"
  GAMMA="${GAMMA:-0.995}"
  TAU="${TAU:-0.95}"
  KL_THRESHOLD="${KL_THRESHOLD:-0.012}"
  ENTROPY_COEF="${ENTROPY_COEF:-0.0005}"
  E_CLIP="${E_CLIP:-0.2}"
  GRAD_NORM="${GRAD_NORM:-1.0}"
elif [ "$TASK" = "Dextrah-Bimanual-YAM-Cube-Grasp" ] \
  || [ "$TASK" = "Dextrah-Single-YAM-Multi-Object-Grasp" ] \
  || [ "$TASK" = "Dextrah-Single-YAM-Tabletop-Clutter-Grasp" ]; then
  NUM_ENVS="${NUM_ENVS:-1024}"
  MINIBATCH_SIZE="${MINIBATCH_SIZE:-16384}"
  CENTRAL_VALUE_MINIBATCH_SIZE="${CENTRAL_VALUE_MINIBATCH_SIZE:-$MINIBATCH_SIZE}"
  LEARNING_RATE="${LEARNING_RATE:-0.0002}"
  CENTRAL_VALUE_LEARNING_RATE="${CENTRAL_VALUE_LEARNING_RATE:-0.0001}"
  HORIZON_LENGTH="${HORIZON_LENGTH:-64}"
  MINI_EPOCHS="${MINI_EPOCHS:-4}"
  SAVE_FREQUENCY="${SAVE_FREQUENCY:-25}"
  GAMMA="${GAMMA:-0.995}"
  TAU="${TAU:-0.95}"
  KL_THRESHOLD="${KL_THRESHOLD:-0.012}"
  ENTROPY_COEF="${ENTROPY_COEF:-0.0005}"
  E_CLIP="${E_CLIP:-0.2}"
  GRAD_NORM="${GRAD_NORM:-1.0}"
elif [ "$TASK" = "Dextrah-Franka-Multi-Object-RGB-Grasp" ]; then
  NUM_ENVS="${NUM_ENVS:-256}"
  MINIBATCH_SIZE="${MINIBATCH_SIZE:-4096}"
  CENTRAL_VALUE_MINIBATCH_SIZE="${CENTRAL_VALUE_MINIBATCH_SIZE:-$MINIBATCH_SIZE}"
  LEARNING_RATE="${LEARNING_RATE:-0.0001}"
  CENTRAL_VALUE_LEARNING_RATE="${CENTRAL_VALUE_LEARNING_RATE:-0.0001}"
  HORIZON_LENGTH="${HORIZON_LENGTH:-32}"
  MINI_EPOCHS="${MINI_EPOCHS:-3}"
  SAVE_FREQUENCY="${SAVE_FREQUENCY:-25}"
  GAMMA="${GAMMA:-0.995}"
  TAU="${TAU:-0.95}"
  KL_THRESHOLD="${KL_THRESHOLD:-0.012}"
  ENTROPY_COEF="${ENTROPY_COEF:-0.0005}"
  E_CLIP="${E_CLIP:-0.2}"
  GRAD_NORM="${GRAD_NORM:-1.0}"
else
  NUM_ENVS="${NUM_ENVS:-4096}"
  MINIBATCH_SIZE="${MINIBATCH_SIZE:-16384}"
  CENTRAL_VALUE_MINIBATCH_SIZE="${CENTRAL_VALUE_MINIBATCH_SIZE:-$MINIBATCH_SIZE}"
  LEARNING_RATE="${LEARNING_RATE:-0.0001}"
  CENTRAL_VALUE_LEARNING_RATE="${CENTRAL_VALUE_LEARNING_RATE:-0.00005}"
  HORIZON_LENGTH="${HORIZON_LENGTH:-16}"
  MINI_EPOCHS="${MINI_EPOCHS:-4}"
  SAVE_FREQUENCY="${SAVE_FREQUENCY:-10}"
  GAMMA="${GAMMA:-0.998}"
  TAU="${TAU:-0.95}"
  KL_THRESHOLD="${KL_THRESHOLD:-0.013}"
  ENTROPY_COEF="${ENTROPY_COEF:-0.002}"
  E_CLIP="${E_CLIP:-0.2}"
  GRAD_NORM="${GRAD_NORM:-1.0}"
fi
if [ -z "$USE_CUDA_GRAPH" ]; then
  if [ "$TASK" = "Dextrah-Franka-Multi-Object-RGB-Grasp" ]; then
    USE_CUDA_GRAPH="False"
  else
    USE_CUDA_GRAPH="True"
  fi
fi
SIGMA_INIT_VAL="${SIGMA_INIT_VAL:-0}"
STAR_RESET_NEAR_HAND_PROBABILITY="${STAR_RESET_NEAR_HAND_PROBABILITY:-0.0}"
STAR_RESET_NEAR_HAND_X="${STAR_RESET_NEAR_HAND_X:--0.360}"
STAR_RESET_NEAR_HAND_Y="${STAR_RESET_NEAR_HAND_Y:--0.120}"
STAR_RESET_NEAR_HAND_XY_NOISE="${STAR_RESET_NEAR_HAND_XY_NOISE:-0.020}"
CUBE_SPAWN_XY_RANDOMIZATION="${CUBE_SPAWN_XY_RANDOMIZATION:-0.08}"
OBJECT_ASSET_MANIFEST_PATH="${OBJECT_ASSET_MANIFEST_PATH:-}"
OBJECT_ASSETS_DIR="${OBJECT_ASSETS_DIR:-}"
MAX_OBJECTS="${MAX_OBJECTS:-0}"
OBJECT_ASSET_ASSIGNMENT="${OBJECT_ASSET_ASSIGNMENT:-random}"
OBJECT_SPAWN_CENTER_OFFSET_X="${OBJECT_SPAWN_CENTER_OFFSET_X:-0.05}"
OBJECT_SPAWN_CENTER_OFFSET_Y="${OBJECT_SPAWN_CENTER_OFFSET_Y:-0.0}"
OBJECT_SPAWN_XY_RANDOMIZATION="${OBJECT_SPAWN_XY_RANDOMIZATION:-0.10}"
OBJECT_SPAWN_YAW_RANDOMIZATION_DEG="${OBJECT_SPAWN_YAW_RANDOMIZATION_DEG:-180.0}"
OBJECT_STABLE_POSE_ENABLED="${OBJECT_STABLE_POSE_ENABLED:-False}"
OBJECT_STABLE_POSE_CACHE_DIR="${OBJECT_STABLE_POSE_CACHE_DIR:-}"
OBJECT_STABLE_POSE_COUNT="${OBJECT_STABLE_POSE_COUNT:-1}"
OBJECT_STABLE_POSE_RANDOMIZE="${OBJECT_STABLE_POSE_RANDOMIZE:-True}"
OBJECT_STABLE_POSE_ALLOW_MISSING="${OBJECT_STABLE_POSE_ALLOW_MISSING:-False}"
TABLETOP_CLUTTER_ASSET_MANIFEST_PATH="${TABLETOP_CLUTTER_ASSET_MANIFEST_PATH:-}"
TABLETOP_CLUTTER_ASSETS_DIR="${TABLETOP_CLUTTER_ASSETS_DIR:-}"
TABLETOP_CLUTTER_MAX_OBJECTS="${TABLETOP_CLUTTER_MAX_OBJECTS:-}"
TABLETOP_CLUTTER_OBJECT_COUNT="${TABLETOP_CLUTTER_OBJECT_COUNT:-}"
TABLETOP_CLUTTER_ASSET_ASSIGNMENT="${TABLETOP_CLUTTER_ASSET_ASSIGNMENT:-}"
TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION="${TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION:-}"
TABLETOP_CLUTTER_SPAWN_YAW_RANDOMIZATION_DEG="${TABLETOP_CLUTTER_SPAWN_YAW_RANDOMIZATION_DEG:-}"
TABLETOP_CLUTTER_SPAWN_Z_JITTER="${TABLETOP_CLUTTER_SPAWN_Z_JITTER:-}"
OBJECT_DENSITY="${OBJECT_DENSITY:-}"
OBJECT_STATIC_FRICTION="${OBJECT_STATIC_FRICTION:-}"
OBJECT_DYNAMIC_FRICTION="${OBJECT_DYNAMIC_FRICTION:-}"
OBJECT_CONTACT_OFFSET="${OBJECT_CONTACT_OFFSET:-}"
OBJECT_REST_OFFSET="${OBJECT_REST_OFFSET:-}"
OBJECT_SOLVER_POSITION_ITERATIONS="${OBJECT_SOLVER_POSITION_ITERATIONS:-}"
OBJECT_SOLVER_VELOCITY_ITERATIONS="${OBJECT_SOLVER_VELOCITY_ITERATIONS:-}"
OBJECT_LINEAR_DAMPING="${OBJECT_LINEAR_DAMPING:-}"
OBJECT_ANGULAR_DAMPING="${OBJECT_ANGULAR_DAMPING:-}"
OBJECT_MAX_DEPENETRATION_VELOCITY="${OBJECT_MAX_DEPENETRATION_VELOCITY:-}"
GRASP_PRIOR_RESET_ENABLED="${GRASP_PRIOR_RESET_ENABLED:-False}"
GRASP_PRIOR_LIBRARY_PATH="${GRASP_PRIOR_LIBRARY_PATH:-}"
GRASP_PRIOR_LIBRARY_DIR="${GRASP_PRIOR_LIBRARY_DIR:-}"
GRASP_PRIOR_VERIFIED_INDICES_PATH="${GRASP_PRIOR_VERIFIED_INDICES_PATH:-}"
GRASP_PRIOR_VERIFIED_ALLOW_UNCOVERED="${GRASP_PRIOR_VERIFIED_ALLOW_UNCOVERED:-False}"
GRASP_PRIOR_ALLOW_MISSING="${GRASP_PRIOR_ALLOW_MISSING:-False}"
GRASP_PRIOR_RESET_ATTEMPTS="${GRASP_PRIOR_RESET_ATTEMPTS:-1}"
GRASP_PRIOR_RESET_CANDIDATE_COUNT="${GRASP_PRIOR_RESET_CANDIDATE_COUNT:-16}"
GRASP_PRIOR_RESET_REQUIRE_TOPDOWN="${GRASP_PRIOR_RESET_REQUIRE_TOPDOWN:-True}"
DEFAULT_GRASP_PRIOR_RESET_MIN_PREGRASP_Z="0.70"
if [ "$TASK" = "Dextrah-Franka-Multi-Object-Grasp" ] || [ "$TASK" = "Dextrah-Franka-Multi-Object-RGB-Grasp" ]; then
  DEFAULT_GRASP_PRIOR_RESET_MIN_PREGRASP_Z="0.45"
fi
GRASP_PRIOR_RESET_MIN_PREGRASP_Z="${GRASP_PRIOR_RESET_MIN_PREGRASP_Z:-$DEFAULT_GRASP_PRIOR_RESET_MIN_PREGRASP_Z}"
GRASP_PRIOR_RESET_REQUIRE_DOWNWARD_TOOL_Z="${GRASP_PRIOR_RESET_REQUIRE_DOWNWARD_TOOL_Z:-True}"
GRASP_PRIOR_RESET_MIN_DOWNWARD_TOOL_Z="${GRASP_PRIOR_RESET_MIN_DOWNWARD_TOOL_Z:-0.45}"
GRASP_PRIOR_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER="${GRASP_PRIOR_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER:--0.02}"
GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC="${GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC:-0.30}"
GRASP_PRIOR_RESET_MIN_WIDTH="${GRASP_PRIOR_RESET_MIN_WIDTH:-0.008}"
GRASP_PRIOR_RESET_QUALITY_MAX_FINGER_CENTER_DIST="${GRASP_PRIOR_RESET_QUALITY_MAX_FINGER_CENTER_DIST:-}"
GRASP_PRIOR_RESET_QUALITY_MAX_TIP_CENTER_DIST="${GRASP_PRIOR_RESET_QUALITY_MAX_TIP_CENTER_DIST:-}"
GRASP_PRIOR_RESET_QUALITY_MAX_TIP_MAX_DIST="${GRASP_PRIOR_RESET_QUALITY_MAX_TIP_MAX_DIST:-}"
GRASP_PRIOR_RESET_IK_ITERATIONS="${GRASP_PRIOR_RESET_IK_ITERATIONS:-}"
GRASP_PRIOR_RESET_IK_DAMPING="${GRASP_PRIOR_RESET_IK_DAMPING:-}"
GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP="${GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP:-}"
GRASP_PRIOR_RESET_IK_POS_TOLERANCE="${GRASP_PRIOR_RESET_IK_POS_TOLERANCE:-}"
GRASP_PRIOR_RESET_IK_ROT_TOLERANCE="${GRASP_PRIOR_RESET_IK_ROT_TOLERANCE:-}"
GRASP_PRIOR_PREGRASP_OFFSET="${GRASP_PRIOR_PREGRASP_OFFSET:-}"
GRASP_PRIOR_ACTION_WARMSTART_ENABLED="${GRASP_PRIOR_ACTION_WARMSTART_ENABLED:-False}"
GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS="${GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS:-16}"
GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS="${GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS:-12}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS:-12}"
GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH="${GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH:-0.025}"
GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH="${GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH:-True}"
GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN="${GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN:-0.003}"
GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH="${GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z:-0.15}"
GRASP_PRIOR_ACTION_WARMSTART_GAIN="${GRASP_PRIOR_ACTION_WARMSTART_GAIN:-8.0}"
GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION="${GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION:-1.0}"
GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION="${GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION:-True}"
GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR="${GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN:--1.0}"
GRASP_PRIOR_ACTION_WARMSTART_REQUIRE_CURRENT_LIFT_READY="${GRASP_PRIOR_ACTION_WARMSTART_REQUIRE_CURRENT_LIFT_READY:-}"
GRASP_PRIOR_ACTION_PRIOR_REWARD_ENABLED="${GRASP_PRIOR_ACTION_PRIOR_REWARD_ENABLED:-False}"
GRASP_PRIOR_ACTION_PRIOR_REWARD_WEIGHT="${GRASP_PRIOR_ACTION_PRIOR_REWARD_WEIGHT:-2.0}"
GRASP_PRIOR_ACTION_PRIOR_REWARD_SHARPNESS="${GRASP_PRIOR_ACTION_PRIOR_REWARD_SHARPNESS:-2.0}"
DEXTRAH_RLGAMES_JSONL_METRICS="${DEXTRAH_RLGAMES_JSONL_METRICS:-False}"
TRAJECTORY_TRACKING_REFERENCE_PATH="${TRAJECTORY_TRACKING_REFERENCE_PATH:-}"
CUBE_APPROACH_WEIGHT="${CUBE_APPROACH_WEIGHT:-}"
CUBE_ENCLOSURE_WEIGHT="${CUBE_ENCLOSURE_WEIGHT:-}"
CUBE_SIDE_ALIGNMENT_WEIGHT="${CUBE_SIDE_ALIGNMENT_WEIGHT:-}"
CUBE_LIFT_WEIGHT="${CUBE_LIFT_WEIGHT:-}"
CUBE_HEIGHT_TRACKING_WEIGHT="${CUBE_HEIGHT_TRACKING_WEIGHT:-}"
CUBE_XY_STABILITY_WEIGHT="${CUBE_XY_STABILITY_WEIGHT:-}"
CUBE_SUCCESS_BONUS_WEIGHT="${CUBE_SUCCESS_BONUS_WEIGHT:-}"
CUBE_CLOSE_ACTION_WEIGHT="${CUBE_CLOSE_ACTION_WEIGHT:-}"
CUBE_LIFT_ACTION_WEIGHT="${CUBE_LIFT_ACTION_WEIGHT:-}"
CUBE_DESCEND_ACTION_PENALTY_WEIGHT="${CUBE_DESCEND_ACTION_PENALTY_WEIGHT:-}"
CUBE_POSTLIFT_ACTION_GATE_HEIGHT="${CUBE_POSTLIFT_ACTION_GATE_HEIGHT:-}"
CUBE_POSTLIFT_CLOSE_ACTION_WEIGHT="${CUBE_POSTLIFT_CLOSE_ACTION_WEIGHT:-}"
CUBE_POSTLIFT_OPEN_ACTION_PENALTY_WEIGHT="${CUBE_POSTLIFT_OPEN_ACTION_PENALTY_WEIGHT:-}"
CUBE_POSTLIFT_LIFT_ACTION_WEIGHT="${CUBE_POSTLIFT_LIFT_ACTION_WEIGHT:-}"
CUBE_POSTLIFT_DESCEND_ACTION_PENALTY_WEIGHT="${CUBE_POSTLIFT_DESCEND_ACTION_PENALTY_WEIGHT:-}"
CUBE_TABLE_CLEARANCE_PENALTY_WEIGHT="${CUBE_TABLE_CLEARANCE_PENALTY_WEIGHT:-}"
CUBE_GRIPPER_CLOSE_REG_WEIGHT="${CUBE_GRIPPER_CLOSE_REG_WEIGHT:-}"
CUBE_ACTION_PENALTY_WEIGHT="${CUBE_ACTION_PENALTY_WEIGHT:-}"
BIMANUAL_ACTION_PRIOR_REWARD_ENABLED="${BIMANUAL_ACTION_PRIOR_REWARD_ENABLED:-}"
BIMANUAL_ACTION_PRIOR_REWARD_WEIGHT="${BIMANUAL_ACTION_PRIOR_REWARD_WEIGHT:-}"
BIMANUAL_ACTION_PRIOR_REWARD_SHARPNESS="${BIMANUAL_ACTION_PRIOR_REWARD_SHARPNESS:-}"
BIMANUAL_REFERENCE_GAIN="${BIMANUAL_REFERENCE_GAIN:-}"
BIMANUAL_REFERENCE_MAX_ACTION="${BIMANUAL_REFERENCE_MAX_ACTION:-}"
BIMANUAL_REFERENCE_LIFT_GAIN="${BIMANUAL_REFERENCE_LIFT_GAIN:-}"
BIMANUAL_REFERENCE_LIFT_MAX_ACTION="${BIMANUAL_REFERENCE_LIFT_MAX_ACTION:-}"
RGB_TRAIN_BACKBONE="${RGB_TRAIN_BACKBONE:-}"
RGB_ENCODER_BATCH_SIZE="${RGB_ENCODER_BATCH_SIZE:-}"
TRAJECTORY_TRACKING_POSITION_WEIGHT="${TRAJECTORY_TRACKING_POSITION_WEIGHT:-}"
TRAJECTORY_TRACKING_ORIENTATION_WEIGHT="${TRAJECTORY_TRACKING_ORIENTATION_WEIGHT:-}"
TRAJECTORY_TRACKING_GRIPPER_WEIGHT="${TRAJECTORY_TRACKING_GRIPPER_WEIGHT:-}"
TRAJECTORY_TRACKING_CLOSE_ACTION_WEIGHT="${TRAJECTORY_TRACKING_CLOSE_ACTION_WEIGHT:-}"
TRAJECTORY_TRACKING_LIFT_ACTION_WEIGHT="${TRAJECTORY_TRACKING_LIFT_ACTION_WEIGHT:-}"
TRAJECTORY_TRACKING_START_WEIGHT="${TRAJECTORY_TRACKING_START_WEIGHT:-}"
TRAJECTORY_TRACKING_END_WEIGHT="${TRAJECTORY_TRACKING_END_WEIGHT:-}"
AUTO_RESUME="${AUTO_RESUME:-True}"
CHECKPOINT="${CHECKPOINT:-}"
FULL_EXPERIMENT_NAME="${FULL_EXPERIMENT_NAME:-}"
SELF_RELAUNCH="${SELF_RELAUNCH:-True}"
REQUEUE_SIGNAL_WINDOW_SECONDS="${REQUEUE_SIGNAL_WINDOW_SECONDS:-420}"
REQUEUE_ON_EARLY_TERM="${REQUEUE_ON_EARLY_TERM:-False}"
RUN_NAME="${FULL_EXPERIMENT_NAME:-slurm_${SLURM_JOB_ID}}"
LOG_FILE="$NFS_ROOT/slurm_logs/dextrah/teacher_8gpu_${SLURM_JOB_ID}.out"
CODE_COMMIT="${CODE_COMMIT:-}"
if [ -z "$CODE_COMMIT" ] && git -C "$CODE_NFS" rev-parse HEAD >/dev/null 2>&1; then
  CODE_COMMIT="$(git -C "$CODE_NFS" rev-parse HEAD)"
fi
SRUN_PID=""
REQUEUE_SUBMITTED=0

case "$GRASP_PRIOR_RESET_ENABLED" in
  True|true|1|yes|Yes)
    if [ "$TASK" != "Dextrah-Franka-Cube-Grasp" ] \
      && [ "$TASK" != "Dextrah-Franka-Multi-Object-Grasp" ] \
      && [ "$TASK" != "Dextrah-Franka-Tabletop-Clutter-Grasp" ] \
      && [ "$TASK" != "Dextrah-Franka-Multi-Object-RGB-Grasp" ]; then
      echo "GRASP_PRIOR_RESET_ENABLED is only supported for Franka cube or multi-object grasp tasks" >&2
      exit 2
    fi
    if [ "$TASK" = "Dextrah-Franka-Cube-Grasp" ] && [ -z "$GRASP_PRIOR_LIBRARY_PATH" ]; then
      echo "GRASP_PRIOR_RESET_ENABLED requires GRASP_PRIOR_LIBRARY_PATH" >&2
      exit 2
    fi
    ;;
esac
case "$GRASP_PRIOR_ACTION_WARMSTART_ENABLED,$GRASP_PRIOR_ACTION_PRIOR_REWARD_ENABLED" in
  True,*|true,*|1,*|yes,*|Yes,*|*,True|*,true|*,1|*,yes|*,Yes)
    case "$GRASP_PRIOR_RESET_ENABLED" in
      True|true|1|yes|Yes) ;;
      *)
        echo "Grasp-prior action guidance requires GRASP_PRIOR_RESET_ENABLED=True" >&2
        exit 2
        ;;
    esac
    ;;
esac
if [ "$TASK" = "Dextrah-Franka-Cube-Grasp-Traj-Tracking" ] && [ -z "$TRAJECTORY_TRACKING_REFERENCE_PATH" ]; then
  echo "Set TRAJECTORY_TRACKING_REFERENCE_PATH for $TASK; production tracking RL must use an explicit reference."
  exit 2
fi

time_left_to_seconds() {
  local raw="${1// /}"
  if [ -z "$raw" ] || [ "$raw" = "N/A" ] || [ "$raw" = "UNLIMITED" ] || [ "$raw" = "INVALID" ]; then
    echo "-1"
    return 0
  fi

  local days=0
  local clock="$raw"
  if [[ "$clock" == *-* ]]; then
    days="${clock%%-*}"
    clock="${clock#*-}"
  fi

  local p1=0
  local p2=0
  local p3=""
  local hours=0
  local minutes=0
  local seconds=0
  IFS=: read -r p1 p2 p3 <<< "$clock"
  if [ -n "$p3" ]; then
    hours="$p1"
    minutes="$p2"
    seconds="$p3"
  else
    minutes="$p1"
    seconds="$p2"
  fi

  if ! [[ "$days" =~ ^[0-9]+$ && "$hours" =~ ^[0-9]+$ && "$minutes" =~ ^[0-9]+$ && "$seconds" =~ ^[0-9]+$ ]]; then
    echo "-1"
    return 0
  fi
  echo $((10#$days * 86400 + 10#$hours * 3600 + 10#$minutes * 60 + 10#$seconds))
}

current_time_left_seconds() {
  local raw_left=""
  raw_left="$(squeue -h -j "$SLURM_JOB_ID" -o "%L" 2>/dev/null | head -n 1 || true)"
  local parsed
  parsed="$(time_left_to_seconds "$raw_left")"
  if [ "$parsed" -ge 0 ]; then
    echo "$parsed"
    return 0
  fi

  if [[ "${SLURM_JOB_END_TIME:-}" =~ ^[0-9]+$ ]]; then
    local now
    now="$(date +%s)"
    echo $((SLURM_JOB_END_TIME - now))
    return 0
  fi

  echo "-1"
}

should_requeue_job() {
  local reason="${1:-signal}"
  if [ "$SELF_RELAUNCH" != "True" ]; then
    echo "SELF_RELAUNCH=$SELF_RELAUNCH; not requeuing job"
    return 1
  fi

  if [ "$REQUEUE_ON_EARLY_TERM" = "True" ]; then
    return 0
  fi

  local time_left
  time_left="$(current_time_left_seconds)"
  if [ "$time_left" -ge 0 ] && [ "$time_left" -le "$REQUEUE_SIGNAL_WINDOW_SECONDS" ]; then
    return 0
  fi

  echo "Not requeuing DEXTRAH job ${SLURM_JOB_ID} after $reason; time_left=${time_left}s exceeds requeue window ${REQUEUE_SIGNAL_WINDOW_SECONDS}s"
  echo "Set REQUEUE_ON_EARLY_TERM=True to requeue non-walltime TERM signals."
  return 1
}

requeue_job() {
  local reason="${1:-signal}"
  if ! should_requeue_job "$reason"; then
    return 0
  fi

  if [ "$REQUEUE_SUBMITTED" = "1" ]; then
    return 0
  fi
  REQUEUE_SUBMITTED=1

  echo "Requeuing DEXTRAH job ${SLURM_JOB_ID} for run $RUN_NAME after $reason"
  scontrol requeue "$SLURM_JOB_ID" || true
}

handle_signal() {
  local signal_name="$1"

  requeue_job "$signal_name"

  if [ -n "$SRUN_PID" ]; then
    echo "Forwarding $signal_name to srun pid $SRUN_PID"
    kill "-$signal_name" "$SRUN_PID" 2>/dev/null || true
  fi

  if [ "$signal_name" = "INT" ]; then
    exit 130
  fi
  exit 15
}

trap 'handle_signal TERM' TERM
trap 'handle_signal INT' INT

if [ ! -f "$IMAGE" ]; then
  echo "Missing Isaac Lab container image: $IMAGE"
  echo "Submit cluster/sbatch_import_isaaclab_sqsh.sh first."
  exit 2
fi
if [ ! -d "$ENV_ROOT/$ENV_NAME/site" ]; then
  echo "Missing DEXTRAH Python target: $ENV_ROOT/$ENV_NAME/site"
  echo "Submit cluster/sbatch_setup_dextrah_env.sh first."
  exit 2
fi

mkdir -p \
  "$RESULTS_NFS/logs" \
  "$NFS_ROOT/slurm_logs/dextrah" \
  "$CACHE_NFS/kit" "$CACHE_NFS/ov" "$CACHE_NFS/pip" \
  "$CACHE_NFS/torch" \
  "$CACHE_NFS/glcache" "$CACHE_NFS/computecache" \
  "$CACHE_NFS/omni_logs" "$CACHE_NFS/carb_logs" \
  "$CACHE_NFS/data" "$CACHE_NFS/documents"

echo "Running DextrAH privileged FGP teacher training"
echo "SLURM_JOB_ID=$SLURM_JOB_ID"
echo "IMAGE=$IMAGE"
echo "CODE_NFS=$CODE_NFS"
echo "FABRICS_NFS=$FABRICS_NFS"
echo "ISAACLAB_NFS=$ISAACLAB_NFS"
echo "CODE_COMMIT=${CODE_COMMIT:-unknown}"
echo "RESULTS_NFS=$RESULTS_NFS"
echo "NPROC_PER_NODE=$NPROC_PER_NODE"
echo "NUM_ENVS=$NUM_ENVS"
echo "TASK=$TASK"
echo "SEED=$SEED"
echo "MASTER_PORT=$MASTER_PORT"
echo "SEED=$SEED"
echo "DISTRIBUTED=$DISTRIBUTED"
echo "MULTI_GPU=$MULTI_GPU"
echo "LEARNING_RATE=$LEARNING_RATE"
echo "CENTRAL_VALUE_LEARNING_RATE=$CENTRAL_VALUE_LEARNING_RATE"
echo "HORIZON_LENGTH=$HORIZON_LENGTH"
echo "MINIBATCH_SIZE=$MINIBATCH_SIZE"
echo "CENTRAL_VALUE_MINIBATCH_SIZE=$CENTRAL_VALUE_MINIBATCH_SIZE"
echo "MINI_EPOCHS=$MINI_EPOCHS"
echo "GAMMA=$GAMMA"
echo "TAU=$TAU"
echo "KL_THRESHOLD=$KL_THRESHOLD"
echo "ENTROPY_COEF=$ENTROPY_COEF"
echo "E_CLIP=$E_CLIP"
echo "GRAD_NORM=$GRAD_NORM"
echo "SIGMA_INIT_VAL=$SIGMA_INIT_VAL"
echo "STAR_RESET_NEAR_HAND_PROBABILITY=$STAR_RESET_NEAR_HAND_PROBABILITY"
echo "STAR_RESET_NEAR_HAND_X=$STAR_RESET_NEAR_HAND_X"
echo "STAR_RESET_NEAR_HAND_Y=$STAR_RESET_NEAR_HAND_Y"
echo "STAR_RESET_NEAR_HAND_XY_NOISE=$STAR_RESET_NEAR_HAND_XY_NOISE"
echo "CUBE_SPAWN_XY_RANDOMIZATION=$CUBE_SPAWN_XY_RANDOMIZATION"
echo "OBJECT_ASSET_MANIFEST_PATH=$OBJECT_ASSET_MANIFEST_PATH"
echo "OBJECT_ASSETS_DIR=$OBJECT_ASSETS_DIR"
echo "MAX_OBJECTS=$MAX_OBJECTS"
echo "OBJECT_ASSET_ASSIGNMENT=$OBJECT_ASSET_ASSIGNMENT"
echo "OBJECT_SPAWN_CENTER_OFFSET_X=$OBJECT_SPAWN_CENTER_OFFSET_X"
echo "OBJECT_SPAWN_CENTER_OFFSET_Y=$OBJECT_SPAWN_CENTER_OFFSET_Y"
echo "OBJECT_SPAWN_XY_RANDOMIZATION=$OBJECT_SPAWN_XY_RANDOMIZATION"
echo "OBJECT_SPAWN_YAW_RANDOMIZATION_DEG=$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
echo "OBJECT_STABLE_POSE_ENABLED=$OBJECT_STABLE_POSE_ENABLED"
echo "OBJECT_STABLE_POSE_CACHE_DIR=$OBJECT_STABLE_POSE_CACHE_DIR"
echo "OBJECT_STABLE_POSE_COUNT=$OBJECT_STABLE_POSE_COUNT"
echo "OBJECT_STABLE_POSE_RANDOMIZE=$OBJECT_STABLE_POSE_RANDOMIZE"
echo "OBJECT_STABLE_POSE_ALLOW_MISSING=$OBJECT_STABLE_POSE_ALLOW_MISSING"
echo "TABLETOP_CLUTTER_ASSET_MANIFEST_PATH=$TABLETOP_CLUTTER_ASSET_MANIFEST_PATH"
echo "TABLETOP_CLUTTER_ASSETS_DIR=$TABLETOP_CLUTTER_ASSETS_DIR"
echo "TABLETOP_CLUTTER_MAX_OBJECTS=$TABLETOP_CLUTTER_MAX_OBJECTS"
echo "TABLETOP_CLUTTER_OBJECT_COUNT=$TABLETOP_CLUTTER_OBJECT_COUNT"
echo "TABLETOP_CLUTTER_ASSET_ASSIGNMENT=$TABLETOP_CLUTTER_ASSET_ASSIGNMENT"
echo "TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION=$TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION"
echo "TABLETOP_CLUTTER_SPAWN_YAW_RANDOMIZATION_DEG=$TABLETOP_CLUTTER_SPAWN_YAW_RANDOMIZATION_DEG"
echo "TABLETOP_CLUTTER_SPAWN_Z_JITTER=$TABLETOP_CLUTTER_SPAWN_Z_JITTER"
echo "OBJECT_DENSITY=$OBJECT_DENSITY"
echo "OBJECT_STATIC_FRICTION=$OBJECT_STATIC_FRICTION"
echo "OBJECT_DYNAMIC_FRICTION=$OBJECT_DYNAMIC_FRICTION"
echo "OBJECT_CONTACT_OFFSET=$OBJECT_CONTACT_OFFSET"
echo "OBJECT_REST_OFFSET=$OBJECT_REST_OFFSET"
echo "OBJECT_SOLVER_POSITION_ITERATIONS=$OBJECT_SOLVER_POSITION_ITERATIONS"
echo "OBJECT_SOLVER_VELOCITY_ITERATIONS=$OBJECT_SOLVER_VELOCITY_ITERATIONS"
echo "OBJECT_LINEAR_DAMPING=$OBJECT_LINEAR_DAMPING"
echo "OBJECT_ANGULAR_DAMPING=$OBJECT_ANGULAR_DAMPING"
echo "OBJECT_MAX_DEPENETRATION_VELOCITY=$OBJECT_MAX_DEPENETRATION_VELOCITY"
echo "GRASP_PRIOR_RESET_ENABLED=$GRASP_PRIOR_RESET_ENABLED"
echo "GRASP_PRIOR_LIBRARY_PATH=$GRASP_PRIOR_LIBRARY_PATH"
echo "GRASP_PRIOR_LIBRARY_DIR=$GRASP_PRIOR_LIBRARY_DIR"
echo "GRASP_PRIOR_VERIFIED_INDICES_PATH=$GRASP_PRIOR_VERIFIED_INDICES_PATH"
echo "GRASP_PRIOR_VERIFIED_ALLOW_UNCOVERED=$GRASP_PRIOR_VERIFIED_ALLOW_UNCOVERED"
echo "GRASP_PRIOR_ALLOW_MISSING=$GRASP_PRIOR_ALLOW_MISSING"
echo "GRASP_PRIOR_ACTION_WARMSTART_ENABLED=$GRASP_PRIOR_ACTION_WARMSTART_ENABLED"
echo "GRASP_PRIOR_RESET_ATTEMPTS=$GRASP_PRIOR_RESET_ATTEMPTS"
echo "GRASP_PRIOR_RESET_CANDIDATE_COUNT=$GRASP_PRIOR_RESET_CANDIDATE_COUNT"
echo "GRASP_PRIOR_RESET_REQUIRE_TOPDOWN=$GRASP_PRIOR_RESET_REQUIRE_TOPDOWN"
echo "GRASP_PRIOR_RESET_MIN_PREGRASP_Z=$GRASP_PRIOR_RESET_MIN_PREGRASP_Z"
echo "GRASP_PRIOR_RESET_REQUIRE_DOWNWARD_TOOL_Z=$GRASP_PRIOR_RESET_REQUIRE_DOWNWARD_TOOL_Z"
echo "GRASP_PRIOR_RESET_MIN_DOWNWARD_TOOL_Z=$GRASP_PRIOR_RESET_MIN_DOWNWARD_TOOL_Z"
echo "GRASP_PRIOR_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER=$GRASP_PRIOR_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER"
echo "GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC=$GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC"
echo "GRASP_PRIOR_RESET_MIN_WIDTH=$GRASP_PRIOR_RESET_MIN_WIDTH"
echo "GRASP_PRIOR_RESET_QUALITY_MAX_FINGER_CENTER_DIST=$GRASP_PRIOR_RESET_QUALITY_MAX_FINGER_CENTER_DIST"
echo "GRASP_PRIOR_RESET_QUALITY_MAX_TIP_CENTER_DIST=$GRASP_PRIOR_RESET_QUALITY_MAX_TIP_CENTER_DIST"
echo "GRASP_PRIOR_RESET_QUALITY_MAX_TIP_MAX_DIST=$GRASP_PRIOR_RESET_QUALITY_MAX_TIP_MAX_DIST"
echo "GRASP_PRIOR_RESET_IK_ITERATIONS=$GRASP_PRIOR_RESET_IK_ITERATIONS"
echo "GRASP_PRIOR_RESET_IK_DAMPING=$GRASP_PRIOR_RESET_IK_DAMPING"
echo "GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP=$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP"
echo "GRASP_PRIOR_RESET_IK_POS_TOLERANCE=$GRASP_PRIOR_RESET_IK_POS_TOLERANCE"
echo "GRASP_PRIOR_RESET_IK_ROT_TOLERANCE=$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE"
echo "GRASP_PRIOR_PREGRASP_OFFSET=$GRASP_PRIOR_PREGRASP_OFFSET"
echo "GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS=$GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS"
echo "GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS=$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS"
echo "GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH=$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH"
echo "GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH=$GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH"
echo "GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN=$GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
echo "GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH=$GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z"
echo "GRASP_PRIOR_ACTION_WARMSTART_GAIN=$GRASP_PRIOR_ACTION_WARMSTART_GAIN"
echo "GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION=$GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION"
echo "GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION=$GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION"
echo "GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR=$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
echo "GRASP_PRIOR_ACTION_WARMSTART_REQUIRE_CURRENT_LIFT_READY=$GRASP_PRIOR_ACTION_WARMSTART_REQUIRE_CURRENT_LIFT_READY"
echo "GRASP_PRIOR_ACTION_PRIOR_REWARD_ENABLED=$GRASP_PRIOR_ACTION_PRIOR_REWARD_ENABLED"
echo "GRASP_PRIOR_ACTION_PRIOR_REWARD_WEIGHT=$GRASP_PRIOR_ACTION_PRIOR_REWARD_WEIGHT"
echo "GRASP_PRIOR_ACTION_PRIOR_REWARD_SHARPNESS=$GRASP_PRIOR_ACTION_PRIOR_REWARD_SHARPNESS"
echo "DEXTRAH_RLGAMES_JSONL_METRICS=$DEXTRAH_RLGAMES_JSONL_METRICS"
echo "TRAJECTORY_TRACKING_REFERENCE_PATH=$TRAJECTORY_TRACKING_REFERENCE_PATH"
echo "CUBE_APPROACH_WEIGHT=$CUBE_APPROACH_WEIGHT"
echo "CUBE_ENCLOSURE_WEIGHT=$CUBE_ENCLOSURE_WEIGHT"
echo "CUBE_SIDE_ALIGNMENT_WEIGHT=$CUBE_SIDE_ALIGNMENT_WEIGHT"
echo "CUBE_LIFT_WEIGHT=$CUBE_LIFT_WEIGHT"
echo "CUBE_HEIGHT_TRACKING_WEIGHT=$CUBE_HEIGHT_TRACKING_WEIGHT"
echo "CUBE_XY_STABILITY_WEIGHT=$CUBE_XY_STABILITY_WEIGHT"
echo "CUBE_SUCCESS_BONUS_WEIGHT=$CUBE_SUCCESS_BONUS_WEIGHT"
echo "CUBE_CLOSE_ACTION_WEIGHT=$CUBE_CLOSE_ACTION_WEIGHT"
echo "CUBE_LIFT_ACTION_WEIGHT=$CUBE_LIFT_ACTION_WEIGHT"
echo "CUBE_DESCEND_ACTION_PENALTY_WEIGHT=$CUBE_DESCEND_ACTION_PENALTY_WEIGHT"
echo "CUBE_POSTLIFT_ACTION_GATE_HEIGHT=$CUBE_POSTLIFT_ACTION_GATE_HEIGHT"
echo "CUBE_POSTLIFT_CLOSE_ACTION_WEIGHT=$CUBE_POSTLIFT_CLOSE_ACTION_WEIGHT"
echo "CUBE_POSTLIFT_OPEN_ACTION_PENALTY_WEIGHT=$CUBE_POSTLIFT_OPEN_ACTION_PENALTY_WEIGHT"
echo "CUBE_POSTLIFT_LIFT_ACTION_WEIGHT=$CUBE_POSTLIFT_LIFT_ACTION_WEIGHT"
echo "CUBE_POSTLIFT_DESCEND_ACTION_PENALTY_WEIGHT=$CUBE_POSTLIFT_DESCEND_ACTION_PENALTY_WEIGHT"
echo "CUBE_TABLE_CLEARANCE_PENALTY_WEIGHT=$CUBE_TABLE_CLEARANCE_PENALTY_WEIGHT"
echo "CUBE_GRIPPER_CLOSE_REG_WEIGHT=$CUBE_GRIPPER_CLOSE_REG_WEIGHT"
echo "CUBE_ACTION_PENALTY_WEIGHT=$CUBE_ACTION_PENALTY_WEIGHT"
echo "BIMANUAL_ACTION_PRIOR_REWARD_ENABLED=$BIMANUAL_ACTION_PRIOR_REWARD_ENABLED"
echo "BIMANUAL_ACTION_PRIOR_REWARD_WEIGHT=$BIMANUAL_ACTION_PRIOR_REWARD_WEIGHT"
echo "BIMANUAL_ACTION_PRIOR_REWARD_SHARPNESS=$BIMANUAL_ACTION_PRIOR_REWARD_SHARPNESS"
echo "BIMANUAL_REFERENCE_GAIN=$BIMANUAL_REFERENCE_GAIN"
echo "BIMANUAL_REFERENCE_MAX_ACTION=$BIMANUAL_REFERENCE_MAX_ACTION"
echo "BIMANUAL_REFERENCE_LIFT_GAIN=$BIMANUAL_REFERENCE_LIFT_GAIN"
echo "BIMANUAL_REFERENCE_LIFT_MAX_ACTION=$BIMANUAL_REFERENCE_LIFT_MAX_ACTION"
echo "RGB_TRAIN_BACKBONE=$RGB_TRAIN_BACKBONE"
echo "RGB_ENCODER_BATCH_SIZE=$RGB_ENCODER_BATCH_SIZE"
echo "TRAJECTORY_TRACKING_POSITION_WEIGHT=$TRAJECTORY_TRACKING_POSITION_WEIGHT"
echo "TRAJECTORY_TRACKING_ORIENTATION_WEIGHT=$TRAJECTORY_TRACKING_ORIENTATION_WEIGHT"
echo "TRAJECTORY_TRACKING_GRIPPER_WEIGHT=$TRAJECTORY_TRACKING_GRIPPER_WEIGHT"
echo "TRAJECTORY_TRACKING_CLOSE_ACTION_WEIGHT=$TRAJECTORY_TRACKING_CLOSE_ACTION_WEIGHT"
echo "TRAJECTORY_TRACKING_LIFT_ACTION_WEIGHT=$TRAJECTORY_TRACKING_LIFT_ACTION_WEIGHT"
echo "TRAJECTORY_TRACKING_START_WEIGHT=$TRAJECTORY_TRACKING_START_WEIGHT"
echo "TRAJECTORY_TRACKING_END_WEIGHT=$TRAJECTORY_TRACKING_END_WEIGHT"
echo "SAVE_FREQUENCY=$SAVE_FREQUENCY"
echo "AUTO_RESUME=$AUTO_RESUME"
echo "CHECKPOINT=$CHECKPOINT"
echo "FULL_EXPERIMENT_NAME=$FULL_EXPERIMENT_NAME"
echo "SELF_RELAUNCH=$SELF_RELAUNCH"
echo "REQUEUE_SIGNAL_WINDOW_SECONDS=$REQUEUE_SIGNAL_WINDOW_SECONDS"
echo "REQUEUE_ON_EARLY_TERM=$REQUEUE_ON_EARLY_TERM"
echo "RUN_NAME=$RUN_NAME"

srun \
  --ntasks=1 \
  --container-image="$IMAGE" \
  --container-mounts=/dev/shm:/dev/shm,"$CODE_NFS":/code,"$FABRICS_NFS":/fabrics,"$ISAACLAB_NFS":/IsaacLab,"$ENV_ROOT":/envs,"$RESULTS_NFS":/results,"$CACHE_NFS/kit":/isaac-sim/kit/cache,"$CACHE_NFS/ov":/root/.cache/ov,"$CACHE_NFS/pip":/root/.cache/pip,"$CACHE_NFS/torch":/root/.cache/torch,"$CACHE_NFS/glcache":/root/.cache/nvidia/GLCache,"$CACHE_NFS/computecache":/root/.nv/ComputeCache,"$CACHE_NFS/omni_logs":/root/.nvidia-omniverse/logs,"$CACHE_NFS/carb_logs":/isaac-sim/kit/logs/Kit/Isaac-Sim,"$CACHE_NFS/data":/root/.local/share/ov/data,"$CACHE_NFS/documents":/root/Documents \
  --no-container-entrypoint \
  --container-remap-root \
  --container-writable \
  --export=ALL,PYTHONUNBUFFERED=1,HYDRA_FULL_ERROR=1,PYTHONFAULTHANDLER=1,TORCH_SHOW_CPP_STACKTRACES=1,NCCL_DEBUG=INFO,ACCEPT_EULA=Y,PRIVACY_CONSENT=Y \
  bash -lc "
    set -euxo pipefail
    export SITE='/envs/$ENV_NAME/site'
    export PYTHONPATH=\"\$SITE:/code:/fabrics/src\"
    for d in /IsaacLab/source/*; do
      if [ -d \"\$d\" ]; then
        export PYTHONPATH=\"\$d:\$PYTHONPATH\"
      fi
    done
    export MASTER_ADDR=127.0.0.1
    export MASTER_PORT='$MASTER_PORT'
    export WANDB_MODE=offline
    export TORCH_HOME=/root/.cache/torch
    export DEXTRAH_AUTO_RESUME='$AUTO_RESUME'
    export DEXTRAH_RUN_NAME='$RUN_NAME'
    export DEXTRAH_LOG_ROOT=/results/logs
    export DEXTRAH_RLGAMES_JSONL_METRICS='$DEXTRAH_RLGAMES_JSONL_METRICS'
    mkdir -p /isaac-sim/kit/data/Kit/Isaac-Sim/5.0/pip3-envs/default
    mkdir -p /results/logs

    cd /code/dextrah_lab/rl_games
    echo \"CODE_COMMIT=${CODE_COMMIT:-unknown}\"
    echo "code_git_head=$(git -C /code rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "code_git_status_short_start"
    git -C /code status --short 2>/dev/null || true
    echo "code_git_status_short_end"

    /isaac-sim/python.sh - <<'PY'
import sys
import torch
import isaaclab
import fabrics_sim
import dextrah_lab
print('python', sys.version)
print('torch', torch.__version__, 'cuda_available', torch.cuda.is_available(), 'device_count', torch.cuda.device_count())
print('isaaclab', isaaclab.__file__)
print('fabrics_sim', fabrics_sim.__file__)
print('dextrah_lab', dextrah_lab.__file__)
PY

    MAX_ITER_ARGS=()
    if [ -n '$MAX_ITERATIONS' ]; then
      MAX_ITER_ARGS=(--max_iterations '$MAX_ITERATIONS')
    fi

    CAMERA_ARGS=()
    if [ '$TASK' = 'Dextrah-Franka-Multi-Object-RGB-Grasp' ]; then
      CAMERA_ARGS=(--enable_cameras)
    fi

    DISTRIBUTED_ARGS=()
    if [ '$DISTRIBUTED' = 'True' ]; then
      DISTRIBUTED_ARGS=(--distributed)
    fi

    RESUME_ARGS=()
    if [ -n '$CHECKPOINT' ]; then
      RESUME_ARGS=(--checkpoint '$CHECKPOINT')
    elif [ '$AUTO_RESUME' = 'True' ]; then
      RESUME_ARGS=(--auto_resume)
    fi

    CENTRAL_VALUE_AGENT_OVERRIDES=()
    if [ '$TASK' != 'Dextrah-Franka-Multi-Object-RGB-Grasp' ]; then
      CENTRAL_VALUE_AGENT_OVERRIDES=(
        agent.params.config.central_value_config.minibatch_size='$CENTRAL_VALUE_MINIBATCH_SIZE'
        agent.params.config.central_value_config.learning_rate='$CENTRAL_VALUE_LEARNING_RATE'
        agent.params.config.central_value_config.kl_threshold='$KL_THRESHOLD'
      )
    fi

    RGB_AGENT_OVERRIDES=()
    if [ '$TASK' = 'Dextrah-Franka-Multi-Object-RGB-Grasp' ]; then
      if [ -n '$RGB_TRAIN_BACKBONE' ]; then
        RGB_AGENT_OVERRIDES+=(agent.params.network.rgb.train_backbone='$RGB_TRAIN_BACKBONE')
      fi
      if [ -n '$RGB_ENCODER_BATCH_SIZE' ]; then
        RGB_AGENT_OVERRIDES+=(agent.params.network.rgb.encoder_batch_size='$RGB_ENCODER_BATCH_SIZE')
      fi
    fi

    PRIOR_RESET_OVERRIDES=()
    case '$GRASP_PRIOR_RESET_ENABLED' in
      True|true|1|yes|Yes)
        if [ '$TASK' = 'Dextrah-Franka-Multi-Object-Grasp' ] \
          || [ '$TASK' = 'Dextrah-Franka-Tabletop-Clutter-Grasp' ] \
          || [ '$TASK' = 'Dextrah-Franka-Multi-Object-RGB-Grasp' ]; then
          PRIOR_RESET_OVERRIDES=(
            env.grasp_prior_reset_enabled=True
            env.grasp_prior_allow_missing='$GRASP_PRIOR_ALLOW_MISSING'
            env.grasp_prior_reset_attempts='$GRASP_PRIOR_RESET_ATTEMPTS'
            env.grasp_prior_reset_candidate_count='$GRASP_PRIOR_RESET_CANDIDATE_COUNT'
            env.grasp_prior_reset_require_topdown='$GRASP_PRIOR_RESET_REQUIRE_TOPDOWN'
            env.grasp_prior_reset_min_pregrasp_z='$GRASP_PRIOR_RESET_MIN_PREGRASP_Z'
            env.grasp_prior_reset_require_downward_tool_z='$GRASP_PRIOR_RESET_REQUIRE_DOWNWARD_TOOL_Z'
            env.grasp_prior_reset_min_downward_tool_z='$GRASP_PRIOR_RESET_MIN_DOWNWARD_TOOL_Z'
            env.grasp_prior_reset_min_contact_height_above_center='$GRASP_PRIOR_RESET_MIN_CONTACT_HEIGHT_ABOVE_CENTER'
            env.grasp_prior_reset_max_center_distance_frac='$GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC'
            env.grasp_prior_reset_min_width='$GRASP_PRIOR_RESET_MIN_WIDTH'
          )
          if [ -n '$GRASP_PRIOR_RESET_QUALITY_MAX_FINGER_CENTER_DIST' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_quality_max_finger_center_dist='$GRASP_PRIOR_RESET_QUALITY_MAX_FINGER_CENTER_DIST')
          fi
          if [ -n '$GRASP_PRIOR_RESET_QUALITY_MAX_TIP_CENTER_DIST' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_quality_max_tip_center_dist='$GRASP_PRIOR_RESET_QUALITY_MAX_TIP_CENTER_DIST')
          fi
          if [ -n '$GRASP_PRIOR_RESET_QUALITY_MAX_TIP_MAX_DIST' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_quality_max_tip_max_dist='$GRASP_PRIOR_RESET_QUALITY_MAX_TIP_MAX_DIST')
          fi
          if [ -n '$GRASP_PRIOR_LIBRARY_DIR' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_library_dir='$GRASP_PRIOR_LIBRARY_DIR')
          fi
          if [ -n '$GRASP_PRIOR_VERIFIED_INDICES_PATH' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_verified_indices_path='$GRASP_PRIOR_VERIFIED_INDICES_PATH')
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_verified_allow_uncovered='$GRASP_PRIOR_VERIFIED_ALLOW_UNCOVERED')
          fi
          if [ -n '$GRASP_PRIOR_PREGRASP_OFFSET' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_pregrasp_offset='$GRASP_PRIOR_PREGRASP_OFFSET')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_ITERATIONS' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_iterations='$GRASP_PRIOR_RESET_IK_ITERATIONS')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_DAMPING' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_damping='$GRASP_PRIOR_RESET_IK_DAMPING')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_max_joint_step='$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_POS_TOLERANCE' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_pos_tolerance='$GRASP_PRIOR_RESET_IK_POS_TOLERANCE')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_rot_tolerance='$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE')
          fi
        else
          PRIOR_RESET_OVERRIDES=(
            env.grasp_prior_reset_enabled=True
            env.grasp_prior_library_path='$GRASP_PRIOR_LIBRARY_PATH'
          )
          if [ -n '$GRASP_PRIOR_PREGRASP_OFFSET' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_pregrasp_offset='$GRASP_PRIOR_PREGRASP_OFFSET')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_ITERATIONS' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_iterations='$GRASP_PRIOR_RESET_IK_ITERATIONS')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_DAMPING' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_damping='$GRASP_PRIOR_RESET_IK_DAMPING')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_max_joint_step='$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_POS_TOLERANCE' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_pos_tolerance='$GRASP_PRIOR_RESET_IK_POS_TOLERANCE')
          fi
          if [ -n '$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE' ]; then
            PRIOR_RESET_OVERRIDES+=(env.grasp_prior_reset_ik_rot_tolerance='$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE')
          fi
        fi
        ;;
    esac

    TASK_OVERRIDES=()
    append_env_override() {
      local field=\"\$1\"
      local value=\"\$2\"
      if [ -n \"\$value\" ]; then
        TASK_OVERRIDES+=(env.\"\$field\"=\"\$value\")
      fi
    }
    append_franka_cube_reward_overrides() {
      append_env_override cube_approach_weight '$CUBE_APPROACH_WEIGHT'
      append_env_override cube_enclosure_weight '$CUBE_ENCLOSURE_WEIGHT'
      append_env_override cube_side_alignment_weight '$CUBE_SIDE_ALIGNMENT_WEIGHT'
      append_env_override cube_lift_weight '$CUBE_LIFT_WEIGHT'
      append_env_override cube_height_tracking_weight '$CUBE_HEIGHT_TRACKING_WEIGHT'
      append_env_override cube_xy_stability_weight '$CUBE_XY_STABILITY_WEIGHT'
      append_env_override cube_success_bonus_weight '$CUBE_SUCCESS_BONUS_WEIGHT'
      append_env_override cube_close_action_weight '$CUBE_CLOSE_ACTION_WEIGHT'
      append_env_override cube_lift_action_weight '$CUBE_LIFT_ACTION_WEIGHT'
      append_env_override cube_descend_action_penalty_weight '$CUBE_DESCEND_ACTION_PENALTY_WEIGHT'
      append_env_override cube_postlift_action_gate_height '$CUBE_POSTLIFT_ACTION_GATE_HEIGHT'
      append_env_override cube_postlift_close_action_weight '$CUBE_POSTLIFT_CLOSE_ACTION_WEIGHT'
      append_env_override cube_postlift_open_action_penalty_weight '$CUBE_POSTLIFT_OPEN_ACTION_PENALTY_WEIGHT'
      append_env_override cube_postlift_lift_action_weight '$CUBE_POSTLIFT_LIFT_ACTION_WEIGHT'
      append_env_override cube_postlift_descend_action_penalty_weight '$CUBE_POSTLIFT_DESCEND_ACTION_PENALTY_WEIGHT'
      append_env_override cube_table_clearance_penalty_weight '$CUBE_TABLE_CLEARANCE_PENALTY_WEIGHT'
      append_env_override cube_gripper_close_reg_weight '$CUBE_GRIPPER_CLOSE_REG_WEIGHT'
      append_env_override cube_action_penalty_weight '$CUBE_ACTION_PENALTY_WEIGHT'
    }
    append_bimanual_action_prior_overrides() {
      append_env_override bimanual_action_prior_reward_enabled '$BIMANUAL_ACTION_PRIOR_REWARD_ENABLED'
      append_env_override bimanual_action_prior_reward_weight '$BIMANUAL_ACTION_PRIOR_REWARD_WEIGHT'
      append_env_override bimanual_action_prior_reward_sharpness '$BIMANUAL_ACTION_PRIOR_REWARD_SHARPNESS'
      append_env_override bimanual_reference_gain '$BIMANUAL_REFERENCE_GAIN'
      append_env_override bimanual_reference_max_action '$BIMANUAL_REFERENCE_MAX_ACTION'
      append_env_override bimanual_reference_lift_gain '$BIMANUAL_REFERENCE_LIFT_GAIN'
      append_env_override bimanual_reference_lift_max_action '$BIMANUAL_REFERENCE_LIFT_MAX_ACTION'
    }
    append_trajectory_tracking_reward_overrides() {
      append_env_override trajectory_tracking_position_weight '$TRAJECTORY_TRACKING_POSITION_WEIGHT'
      append_env_override trajectory_tracking_orientation_weight '$TRAJECTORY_TRACKING_ORIENTATION_WEIGHT'
      append_env_override trajectory_tracking_gripper_weight '$TRAJECTORY_TRACKING_GRIPPER_WEIGHT'
      append_env_override trajectory_tracking_close_action_weight '$TRAJECTORY_TRACKING_CLOSE_ACTION_WEIGHT'
      append_env_override trajectory_tracking_lift_action_weight '$TRAJECTORY_TRACKING_LIFT_ACTION_WEIGHT'
      append_env_override trajectory_tracking_start_weight '$TRAJECTORY_TRACKING_START_WEIGHT'
      append_env_override trajectory_tracking_end_weight '$TRAJECTORY_TRACKING_END_WEIGHT'
    }
    append_multi_object_physics_overrides() {
      append_env_override object_density '$OBJECT_DENSITY'
      append_env_override object_static_friction '$OBJECT_STATIC_FRICTION'
      append_env_override object_dynamic_friction '$OBJECT_DYNAMIC_FRICTION'
      append_env_override object_contact_offset '$OBJECT_CONTACT_OFFSET'
      append_env_override object_rest_offset '$OBJECT_REST_OFFSET'
      append_env_override object_solver_position_iterations '$OBJECT_SOLVER_POSITION_ITERATIONS'
      append_env_override object_solver_velocity_iterations '$OBJECT_SOLVER_VELOCITY_ITERATIONS'
      append_env_override object_linear_damping '$OBJECT_LINEAR_DAMPING'
      append_env_override object_angular_damping '$OBJECT_ANGULAR_DAMPING'
      append_env_override object_max_depenetration_velocity '$OBJECT_MAX_DEPENETRATION_VELOCITY'
    }
    append_tabletop_clutter_overrides() {
      append_env_override tabletop_clutter_asset_manifest_path '$TABLETOP_CLUTTER_ASSET_MANIFEST_PATH'
      append_env_override tabletop_clutter_assets_dir '$TABLETOP_CLUTTER_ASSETS_DIR'
      append_env_override tabletop_clutter_max_objects '$TABLETOP_CLUTTER_MAX_OBJECTS'
      append_env_override tabletop_clutter_object_count '$TABLETOP_CLUTTER_OBJECT_COUNT'
      append_env_override tabletop_clutter_asset_assignment '$TABLETOP_CLUTTER_ASSET_ASSIGNMENT'
      append_env_override tabletop_clutter_spawn_xy_randomization '$TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION'
      append_env_override tabletop_clutter_spawn_yaw_randomization_deg '$TABLETOP_CLUTTER_SPAWN_YAW_RANDOMIZATION_DEG'
      append_env_override tabletop_clutter_spawn_z_jitter '$TABLETOP_CLUTTER_SPAWN_Z_JITTER'
    }
    append_grasp_prior_reference_sequence_overrides() {
      TASK_OVERRIDES+=(
        env.grasp_prior_action_warmstart_approach_steps='$GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS'
        env.grasp_prior_action_warmstart_close_steps='$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS'
        env.grasp_prior_action_warmstart_lift_steps='$GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS'
        env.grasp_prior_action_warmstart_close_width='$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH'
        env.grasp_prior_action_warmstart_use_prior_close_width='$GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH'
        env.grasp_prior_action_warmstart_prior_close_width_margin='$GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN'
        env.grasp_prior_action_warmstart_min_close_width='$GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH'
        env.grasp_prior_action_warmstart_lift_action_z='$GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z'
        env.grasp_prior_action_warmstart_gain='$GRASP_PRIOR_ACTION_WARMSTART_GAIN'
        env.grasp_prior_action_warmstart_max_position_action='$GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION'
        env.grasp_prior_action_warmstart_track_orientation='$GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION'
        env.grasp_prior_action_warmstart_close_max_ee_error='$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR'
        env.grasp_prior_action_warmstart_lift_max_ee_error='$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR'
        env.grasp_prior_action_warmstart_lift_max_finger_center_dist='$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST'
        env.grasp_prior_action_warmstart_lift_closed_width_margin='$GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN'
      )
      if [ -n '$GRASP_PRIOR_ACTION_WARMSTART_REQUIRE_CURRENT_LIFT_READY' ]; then
        TASK_OVERRIDES+=(env.grasp_prior_action_warmstart_require_current_lift_ready='$GRASP_PRIOR_ACTION_WARMSTART_REQUIRE_CURRENT_LIFT_READY')
      fi
    }
    append_grasp_prior_action_guidance_overrides() {
      case '$GRASP_PRIOR_ACTION_WARMSTART_ENABLED' in
        True|true|1|yes|Yes)
          TASK_OVERRIDES+=(env.grasp_prior_action_warmstart_enabled=True)
          append_grasp_prior_reference_sequence_overrides
          ;;
      esac
      case '$GRASP_PRIOR_ACTION_PRIOR_REWARD_ENABLED' in
        True|true|1|yes|Yes)
          TASK_OVERRIDES+=(
            env.grasp_prior_action_prior_reward_enabled=True
            env.grasp_prior_action_prior_reward_weight='$GRASP_PRIOR_ACTION_PRIOR_REWARD_WEIGHT'
            env.grasp_prior_action_prior_reward_sharpness='$GRASP_PRIOR_ACTION_PRIOR_REWARD_SHARPNESS'
          )
          case '$GRASP_PRIOR_ACTION_WARMSTART_ENABLED' in
            True|true|1|yes|Yes) ;;
            *) append_grasp_prior_reference_sequence_overrides ;;
          esac
          ;;
      esac
    }
    if [ '$TASK' = 'Dextrah-Cube-Grasp' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.max_pose_angle=45.0
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.enable_adr=False
        'env.adr_custom_cfg_dict.object_spawn.x_width_spawn=[0.08, 0.08]'
        'env.adr_custom_cfg_dict.object_spawn.y_width_spawn=[0.08, 0.08]'
      )
    elif [ '$TASK' = 'Dextrah-Franka-Star-Kitting' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.star_reset_near_hand_probability='$STAR_RESET_NEAR_HAND_PROBABILITY'
        env.star_reset_near_hand_x='$STAR_RESET_NEAR_HAND_X'
        env.star_reset_near_hand_y='$STAR_RESET_NEAR_HAND_Y'
        env.star_reset_near_hand_xy_noise='$STAR_RESET_NEAR_HAND_XY_NOISE'
      )
    elif [ '$TASK' = 'Dextrah-Franka-Cube-Grasp' ] || [ '$TASK' = 'Dextrah-Franka-Cube-Grasp-Traj-Tracking' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.cube_spawn_xy_randomization='$CUBE_SPAWN_XY_RANDOMIZATION'
      )
      append_franka_cube_reward_overrides
      append_grasp_prior_action_guidance_overrides
      if [ -n '$TRAJECTORY_TRACKING_REFERENCE_PATH' ]; then
        TASK_OVERRIDES+=(
          env.trajectory_tracking_reference_path='$TRAJECTORY_TRACKING_REFERENCE_PATH'
        )
      fi
      if [ '$TASK' = 'Dextrah-Franka-Cube-Grasp-Traj-Tracking' ]; then
        append_trajectory_tracking_reward_overrides
      fi
    elif [ '$TASK' = 'Dextrah-Bimanual-YAM-Cube-Grasp' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.cube_spawn_xy_randomization='$CUBE_SPAWN_XY_RANDOMIZATION'
      )
      append_franka_cube_reward_overrides
      append_bimanual_action_prior_overrides
    elif [ '$TASK' = 'Dextrah-Single-YAM-Multi-Object-Grasp' ] || [ '$TASK' = 'Dextrah-Single-YAM-Tabletop-Clutter-Grasp' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.max_objects='$MAX_OBJECTS'
        env.object_asset_assignment='$OBJECT_ASSET_ASSIGNMENT'
        env.object_spawn_center_offset_x='$OBJECT_SPAWN_CENTER_OFFSET_X'
        env.object_spawn_center_offset_y='$OBJECT_SPAWN_CENTER_OFFSET_Y'
        env.object_spawn_xy_randomization='$OBJECT_SPAWN_XY_RANDOMIZATION'
        env.object_spawn_yaw_randomization_deg='$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG'
        env.object_stable_pose_enabled='$OBJECT_STABLE_POSE_ENABLED'
        env.object_stable_pose_count='$OBJECT_STABLE_POSE_COUNT'
        env.object_stable_pose_randomize='$OBJECT_STABLE_POSE_RANDOMIZE'
        env.object_stable_pose_allow_missing='$OBJECT_STABLE_POSE_ALLOW_MISSING'
      )
      append_env_override object_asset_manifest_path '$OBJECT_ASSET_MANIFEST_PATH'
      append_env_override object_assets_dir '$OBJECT_ASSETS_DIR'
      append_env_override object_stable_pose_cache_dir '$OBJECT_STABLE_POSE_CACHE_DIR'
      append_multi_object_physics_overrides
      append_tabletop_clutter_overrides
      append_franka_cube_reward_overrides
      append_bimanual_action_prior_overrides
    elif [ '$TASK' = 'Dextrah-Franka-Multi-Object-Grasp' ] || [ '$TASK' = 'Dextrah-Franka-Tabletop-Clutter-Grasp' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.max_objects='$MAX_OBJECTS'
        env.object_asset_assignment='$OBJECT_ASSET_ASSIGNMENT'
        env.object_spawn_center_offset_x='$OBJECT_SPAWN_CENTER_OFFSET_X'
        env.object_spawn_center_offset_y='$OBJECT_SPAWN_CENTER_OFFSET_Y'
        env.object_spawn_xy_randomization='$OBJECT_SPAWN_XY_RANDOMIZATION'
        env.object_spawn_yaw_randomization_deg='$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG'
        env.object_stable_pose_enabled='$OBJECT_STABLE_POSE_ENABLED'
        env.object_stable_pose_count='$OBJECT_STABLE_POSE_COUNT'
        env.object_stable_pose_randomize='$OBJECT_STABLE_POSE_RANDOMIZE'
        env.object_stable_pose_allow_missing='$OBJECT_STABLE_POSE_ALLOW_MISSING'
      )
      append_env_override object_asset_manifest_path '$OBJECT_ASSET_MANIFEST_PATH'
      append_env_override object_assets_dir '$OBJECT_ASSETS_DIR'
      append_env_override object_stable_pose_cache_dir '$OBJECT_STABLE_POSE_CACHE_DIR'
      append_multi_object_physics_overrides
      append_tabletop_clutter_overrides
      append_franka_cube_reward_overrides
      append_grasp_prior_action_guidance_overrides
    elif [ '$TASK' = 'Dextrah-Franka-Multi-Object-RGB-Grasp' ]; then
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.use_cuda_graph='$USE_CUDA_GRAPH'
        env.max_objects='$MAX_OBJECTS'
        env.object_asset_assignment='$OBJECT_ASSET_ASSIGNMENT'
        env.object_spawn_center_offset_x='$OBJECT_SPAWN_CENTER_OFFSET_X'
        env.object_spawn_center_offset_y='$OBJECT_SPAWN_CENTER_OFFSET_Y'
        env.object_spawn_xy_randomization='$OBJECT_SPAWN_XY_RANDOMIZATION'
        env.object_spawn_yaw_randomization_deg='$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG'
        env.object_stable_pose_enabled='$OBJECT_STABLE_POSE_ENABLED'
        env.object_stable_pose_count='$OBJECT_STABLE_POSE_COUNT'
        env.object_stable_pose_randomize='$OBJECT_STABLE_POSE_RANDOMIZE'
        env.object_stable_pose_allow_missing='$OBJECT_STABLE_POSE_ALLOW_MISSING'
      )
      append_env_override object_asset_manifest_path '$OBJECT_ASSET_MANIFEST_PATH'
      append_env_override object_assets_dir '$OBJECT_ASSETS_DIR'
      append_env_override object_stable_pose_cache_dir '$OBJECT_STABLE_POSE_CACHE_DIR'
      append_multi_object_physics_overrides
      append_franka_cube_reward_overrides
      append_grasp_prior_action_guidance_overrides
    else
      TASK_OVERRIDES=(
        agent.wandb_activate=False
        env.success_for_adr=0.4
        env.objects_dir=visdex_objects
        'env.adr_custom_cfg_dict.fabric_damping.gain=[10.0, 20.0]'
        'env.adr_custom_cfg_dict.reward_weights.finger_curl_reg=[-0.01, -0.01]'
        'env.adr_custom_cfg_dict.reward_weights.lift_weight=[5.0, 0.0]'
        env.max_pose_angle=45.0
        env.use_cuda_graph='$USE_CUDA_GRAPH'
      )
    fi

    TRAIN_ARGS=(
      train.py \
        --headless \
        \"\${CAMERA_ARGS[@]}\" \
        --task='$TASK' \
        --seed '$SEED' \
        \"\${DISTRIBUTED_ARGS[@]}\" \
        \"\${RESUME_ARGS[@]}\" \
        --num_envs '$NUM_ENVS' \
        \"\${MAX_ITER_ARGS[@]}\" \
        agent.params.config.minibatch_size='$MINIBATCH_SIZE' \
        agent.params.config.learning_rate='$LEARNING_RATE' \
        agent.params.config.horizon_length='$HORIZON_LENGTH' \
        agent.params.config.mini_epochs='$MINI_EPOCHS' \
        agent.params.config.gamma='$GAMMA' \
        agent.params.config.tau='$TAU' \
        agent.params.config.kl_threshold='$KL_THRESHOLD' \
        agent.params.config.entropy_coef='$ENTROPY_COEF' \
        agent.params.network.space.continuous.sigma_init.val='$SIGMA_INIT_VAL' \
        agent.params.config.e_clip='$E_CLIP' \
        agent.params.config.grad_norm='$GRAD_NORM' \
        agent.params.config.save_frequency='$SAVE_FREQUENCY' \
        agent.params.config.multi_gpu='$MULTI_GPU' \
        \"\${CENTRAL_VALUE_AGENT_OVERRIDES[@]}\" \
        \"\${RGB_AGENT_OVERRIDES[@]}\" \
        \"\${TASK_OVERRIDES[@]}\"
        \"\${PRIOR_RESET_OVERRIDES[@]}\"
    )

    if [ '$DISTRIBUTED' = 'True' ]; then
      /isaac-sim/python.sh -m torch.distributed.run \
        --nnodes='$NUM_NODES' \
        --nproc_per_node='$NPROC_PER_NODE' \
        --master_addr=127.0.0.1 \
        --master_port='$MASTER_PORT' \
        \"\${TRAIN_ARGS[@]}\"
    else
      /isaac-sim/python.sh \"\${TRAIN_ARGS[@]}\"
    fi
  " &
SRUN_PID=$!
set +e
wait "$SRUN_PID"
SRUN_EXIT=$?
set -e

if [ "$SRUN_EXIT" -ge 128 ]; then
  echo "srun killed by signal $((SRUN_EXIT - 128)) (exit $SRUN_EXIT)"
  requeue_job "srun_exit_$SRUN_EXIT"
  exit 15
elif [ "$SRUN_EXIT" -ne 0 ]; then
  echo "srun exited with code $SRUN_EXIT (training error), NOT requeuing."
  exit "$SRUN_EXIT"
fi

if [ -f "$LOG_FILE" ] && grep -E "Traceback|RuntimeError:|Error executing job with overrides|ChildFailedError|Could not execute <function load" "$LOG_FILE" >/dev/null; then
  echo "Detected training error patterns in $LOG_FILE despite zero srun exit; NOT requeuing."
  exit 1
fi

echo "Training Done"
