#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --account=nvr_lpr_rvp
#SBATCH --gpus-per-node=1
#SBATCH --job-name=dextrah_franka_cube_bc
#SBATCH --partition=batch_singlenode,grizzly,polar,polar3,polar4,interactive_singlenode
#SBATCH --time=0-00:45:00
#SBATCH --mem=160G
#SBATCH --cpus-per-task=16
#SBATCH --output=/lustre/fsw/portfolios/nvr/users/lzha/slurm_logs/dextrah/bc_franka_cube_%j.out

set -euo pipefail

NFS_ROOT="${NFS_ROOT:-/lustre/fsw/portfolios/nvr/users/lzha}"
CODE_NFS="${CODE_NFS:-$NFS_ROOT/src/DEXTRAH}"
FABRICS_NFS="${FABRICS_NFS:-$NFS_ROOT/src/FABRICS}"
ISAACLAB_NFS="${ISAACLAB_NFS:-$NFS_ROOT/src/IsaacLab-v2.2.1}"
IMAGE="${IMAGE:-$NFS_ROOT/cache/isaac_lab_2.2.0.sqsh}"
ENV_ROOT="${ENV_ROOT:-$NFS_ROOT/envs}"
ENV_NAME="${ENV_NAME:-dextrah-isaaclab}"
RESULTS_NFS="${RESULTS_NFS:-$NFS_ROOT/results/dextrah}"
CACHE_NFS="${CACHE_NFS:-$NFS_ROOT/isaac_cache}"

TASK="${TASK:-Dextrah-Franka-Cube-Grasp-Traj-Tracking}"
SLURM_JOB_ID_SAFE="${SLURM_JOB_ID:-manual}"
RUN_NAME="${RUN_NAME:-franka_cube_traj_bc_${SLURM_JOB_ID_SAFE}_$(date +%Y%m%d_%H%M%S)}"
NUM_ENVS="${NUM_ENVS:-8}"
COLLECTION_STEPS="${COLLECTION_STEPS:-520}"
TRAIN_STEPS="${TRAIN_STEPS:-400}"
BATCH_SIZE="${BATCH_SIZE:-1024}"
LEARNING_RATE="${LEARNING_RATE:-0.0001}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.0}"
VALIDATION_FRACTION="${VALIDATION_FRACTION:-0.2}"
LOSS_DIMS="${LOSS_DIMS:-all}"
EVAL_INTERVAL="${EVAL_INTERVAL:-25}"
USE_CUDA_GRAPH="${USE_CUDA_GRAPH:-False}"
SEED="${SEED:-42}"
COLLECTION_ACTION_SOURCE="${COLLECTION_ACTION_SOURCE:-reference_delta}"
ALLOW_DIAGNOSTIC_ACTION_SOURCES="${ALLOW_DIAGNOSTIC_ACTION_SOURCES:-False}"
LABEL_ACTION_SOURCE="${LABEL_ACTION_SOURCE:-reference_delta}"
COLLECTION_TEACHER_ALPHA="${COLLECTION_TEACHER_ALPHA:-0.5}"
COLLECTION_TEACHER_ALPHAS="${COLLECTION_TEACHER_ALPHAS:-}"
COLLECTION_REFERENCE_MIX_Z_ALPHA="${COLLECTION_REFERENCE_MIX_Z_ALPHA:--1.0}"
COLLECTION_REFERENCE_MIX_GRIPPER_ALPHA="${COLLECTION_REFERENCE_MIX_GRIPPER_ALPHA:--1.0}"
HOLD_TRIGGER_MODE="${HOLD_TRIGGER_MODE:-any}"
HOLD_PHASE_START="${HOLD_PHASE_START:-0.67}"
HOLD_TRIGGER_LIFT_HEIGHT="${HOLD_TRIGGER_LIFT_HEIGHT:-0.02}"
HOLD_CONTACT_MAX_FINGER_DIST="${HOLD_CONTACT_MAX_FINGER_DIST:-0.08}"
HOLD_LIFT_HEIGHT="${HOLD_LIFT_HEIGHT:-0.03}"
HOLD_TARGET_POLICY="${HOLD_TARGET_POLICY:-cube_current_plus_trigger_ee_offset}"
HOLD_GRIPPER_ACTION="${HOLD_GRIPPER_ACTION:--0.4}"
REHEARSAL_DATASET_PATHS="${REHEARSAL_DATASET_PATHS:-}"
REHEARSAL_DATASET_NAMES="${REHEARSAL_DATASET_NAMES:-}"
SOURCE_BATCH_MODE="${SOURCE_BATCH_MODE:-random}"
SOURCE_LOSS_WEIGHTS="${SOURCE_LOSS_WEIGHTS:-}"
BEST_SCORE_WEIGHTS="${BEST_SCORE_WEIGHTS:-}"
EARLY_STOP_PATIENCE="${EARLY_STOP_PATIENCE:-0}"
DISTILL_SOURCES="${DISTILL_SOURCES:-}"
DISTILL_LOSS_WEIGHT="${DISTILL_LOSS_WEIGHT:-0.0}"
DISTILL_DIMS="${DISTILL_DIMS:-}"
RESIDUAL_ADAPTER_ENABLED="${RESIDUAL_ADAPTER_ENABLED:-False}"
RESIDUAL_HIDDEN_DIM="${RESIDUAL_HIDDEN_DIM:-64}"
RESIDUAL_MAX_ACTION="${RESIDUAL_MAX_ACTION:-0.5}"
RESIDUAL_PRESERVE_SOURCES="${RESIDUAL_PRESERVE_SOURCES:-}"
RESIDUAL_PRESERVE_WEIGHT="${RESIDUAL_PRESERVE_WEIGHT:-0.0}"
RESIDUAL_L2_WEIGHT="${RESIDUAL_L2_WEIGHT:-0.0}"
RESIDUAL_GATE_ENABLED="${RESIDUAL_GATE_ENABLED:-False}"
RESIDUAL_GATE_HIDDEN_DIM="${RESIDUAL_GATE_HIDDEN_DIM:--1}"
RESIDUAL_GATE_BIAS_INIT="${RESIDUAL_GATE_BIAS_INIT:-0.0}"
RESIDUAL_CONTEXT_FEATURES="${RESIDUAL_CONTEXT_FEATURES:-}"
HANDOFF_SOURCE_ENABLED="${HANDOFF_SOURCE_ENABLED:-False}"
HANDOFF_SOURCE_SOURCES="${HANDOFF_SOURCE_SOURCES:-}"
HANDOFF_SOURCE_NAME="${HANDOFF_SOURCE_NAME:-policy0_success_handoff}"
HANDOFF_TEACHER_ALPHA="${HANDOFF_TEACHER_ALPHA:-0.0}"
HANDOFF_MIN_PHASE="${HANDOFF_MIN_PHASE:-0.55}"
HANDOFF_MAX_PHASE="${HANDOFF_MAX_PHASE:-1.01}"
HANDOFF_MIN_LIFT_HEIGHT="${HANDOFF_MIN_LIFT_HEIGHT:-0.02}"
HANDOFF_MAX_FINGER_DIST="${HANDOFF_MAX_FINGER_DIST:--1.0}"
HANDOFF_REQUIRE_HOLD_ACTIVE="${HANDOFF_REQUIRE_HOLD_ACTIVE:-False}"
HANDOFF_REQUIRE_SUCCESS="${HANDOFF_REQUIRE_SUCCESS:-False}"
HANDOFF_REQUIRE_SAFE_TARGET="${HANDOFF_REQUIRE_SAFE_TARGET:-True}"
HANDOFF_MAX_SAMPLES="${HANDOFF_MAX_SAMPLES:-0}"
SOURCE_PROBE_STEPS="${SOURCE_PROBE_STEPS:-200}"
SOURCE_PROBE_LR="${SOURCE_PROBE_LR:-0.01}"
CUBE_SPAWN_XY_RANDOMIZATION="${CUBE_SPAWN_XY_RANDOMIZATION:-0.08}"
TRAJECTORY_TRACKING_REFERENCE_PATH="${TRAJECTORY_TRACKING_REFERENCE_PATH:-}"
OBJECT_ASSET_MANIFEST_PATH="${OBJECT_ASSET_MANIFEST_PATH:-}"
OBJECT_ASSETS_DIR="${OBJECT_ASSETS_DIR:-}"
MAX_OBJECTS="${MAX_OBJECTS:-0}"
OBJECT_ASSET_ASSIGNMENT="${OBJECT_ASSET_ASSIGNMENT:-random}"
OBJECT_SPAWN_CENTER_OFFSET_X="${OBJECT_SPAWN_CENTER_OFFSET_X:-0.05}"
OBJECT_SPAWN_CENTER_OFFSET_Y="${OBJECT_SPAWN_CENTER_OFFSET_Y:-0.0}"
OBJECT_SPAWN_XY_RANDOMIZATION="${OBJECT_SPAWN_XY_RANDOMIZATION:-0.10}"
OBJECT_SPAWN_YAW_RANDOMIZATION_DEG="${OBJECT_SPAWN_YAW_RANDOMIZATION_DEG:-180.0}"
OBJECT_STABLE_POSE_ENABLED="${OBJECT_STABLE_POSE_ENABLED:-False}"
OBJECT_STABLE_POSE_CACHE_DIR="${OBJECT_STABLE_POSE_CACHE_DIR:-}"
OBJECT_STABLE_POSE_COUNT="${OBJECT_STABLE_POSE_COUNT:-1}"
OBJECT_STABLE_POSE_RANDOMIZE="${OBJECT_STABLE_POSE_RANDOMIZE:-True}"
OBJECT_STABLE_POSE_ALLOW_MISSING="${OBJECT_STABLE_POSE_ALLOW_MISSING:-False}"
GRASP_PRIOR_RESET_ENABLED="${GRASP_PRIOR_RESET_ENABLED:-False}"
GRASP_PRIOR_LIBRARY_DIR="${GRASP_PRIOR_LIBRARY_DIR:-}"
GRASP_PRIOR_VERIFIED_INDICES_PATH="${GRASP_PRIOR_VERIFIED_INDICES_PATH:-}"
GRASP_PRIOR_ALLOW_MISSING="${GRASP_PRIOR_ALLOW_MISSING:-False}"
GRASP_PRIOR_RESET_ATTEMPTS="${GRASP_PRIOR_RESET_ATTEMPTS:-1}"
GRASP_PRIOR_RESET_CANDIDATE_COUNT="${GRASP_PRIOR_RESET_CANDIDATE_COUNT:-16}"
GRASP_PRIOR_RESET_REQUIRE_TOPDOWN="${GRASP_PRIOR_RESET_REQUIRE_TOPDOWN:-True}"
GRASP_PRIOR_RESET_MIN_PREGRASP_Z="${GRASP_PRIOR_RESET_MIN_PREGRASP_Z:-0.45}"
GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC="${GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC:-0.30}"
GRASP_PRIOR_RESET_MIN_WIDTH="${GRASP_PRIOR_RESET_MIN_WIDTH:-0.008}"
GRASP_PRIOR_RESET_IK_ITERATIONS="${GRASP_PRIOR_RESET_IK_ITERATIONS:-}"
GRASP_PRIOR_RESET_IK_DAMPING="${GRASP_PRIOR_RESET_IK_DAMPING:-}"
GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP="${GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP:-}"
GRASP_PRIOR_RESET_IK_POS_TOLERANCE="${GRASP_PRIOR_RESET_IK_POS_TOLERANCE:-}"
GRASP_PRIOR_RESET_IK_ROT_TOLERANCE="${GRASP_PRIOR_RESET_IK_ROT_TOLERANCE:-}"
GRASP_PRIOR_PREGRASP_OFFSET="${GRASP_PRIOR_PREGRASP_OFFSET:-}"
GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS="${GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS:-16}"
GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS="${GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS:-12}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS:-12}"
GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH="${GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH:-0.025}"
GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH="${GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH:-True}"
GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN="${GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN:-0.003}"
GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH="${GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z:-0.15}"
GRASP_PRIOR_ACTION_WARMSTART_GAIN="${GRASP_PRIOR_ACTION_WARMSTART_GAIN:-8.0}"
GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION="${GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION:-1.0}"
GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION="${GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION:-True}"
GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR="${GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST:-0.0}"
GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN="${GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN:--1.0}"
CHECKPOINT="${CHECKPOINT:?Set CHECKPOINT to an RL-Games checkpoint path visible in /results or on the host}"

if { [ "$COLLECTION_ACTION_SOURCE" = "policy_reference_mix" ] || [ "$COLLECTION_ACTION_SOURCE" = "policy_reference_mix_hold" ]; } && [ "$ALLOW_DIAGNOSTIC_ACTION_SOURCES" != "True" ]; then
  echo "COLLECTION_ACTION_SOURCE=$COLLECTION_ACTION_SOURCE is diagnostic-only; set ALLOW_DIAGNOSTIC_ACTION_SOURCES=True to run it deliberately."
  exit 2
fi

RUN_DIR_HOST="$RESULTS_NFS/bc/$RUN_NAME"
RUN_DIR_CONTAINER="/results/bc/$RUN_NAME"
LOG_FILE="$NFS_ROOT/slurm_logs/dextrah/bc_franka_cube_${SLURM_JOB_ID_SAFE}.out"
BC_CHECKPOINT_CONTAINER="$RUN_DIR_CONTAINER/nn/bc_reference_action_imitation.pth"
DATASET_CONTAINER="$RUN_DIR_CONTAINER/reference_action_dataset.pt"

CHECKPOINT_ARG="$CHECKPOINT"
CHECKPOINT_HOST="$CHECKPOINT"
if [[ "$CHECKPOINT" == /results/* ]]; then
  CHECKPOINT_HOST="$RESULTS_NFS/${CHECKPOINT#/results/}"
elif [[ "$CHECKPOINT" == "$RESULTS_NFS"/* ]]; then
  rel_checkpoint="${CHECKPOINT#$RESULTS_NFS/}"
  CHECKPOINT_ARG="/results/$rel_checkpoint"
fi

manifest_host=""
if [ -n "$OBJECT_ASSET_MANIFEST_PATH" ]; then
  if [[ "$OBJECT_ASSET_MANIFEST_PATH" == /results/* ]]; then
    manifest_host="$RESULTS_NFS/${OBJECT_ASSET_MANIFEST_PATH#/results/}"
  elif [[ "$OBJECT_ASSET_MANIFEST_PATH" == "$RESULTS_NFS"/* ]]; then
    rel_manifest="${OBJECT_ASSET_MANIFEST_PATH#$RESULTS_NFS/}"
    OBJECT_ASSET_MANIFEST_PATH="/results/$rel_manifest"
    manifest_host="$RESULTS_NFS/$rel_manifest"
  fi
fi

verified_indices_host=""
if [ -n "$GRASP_PRIOR_VERIFIED_INDICES_PATH" ]; then
  if [[ "$GRASP_PRIOR_VERIFIED_INDICES_PATH" == /results/* ]]; then
    verified_indices_host="$RESULTS_NFS/${GRASP_PRIOR_VERIFIED_INDICES_PATH#/results/}"
  elif [[ "$GRASP_PRIOR_VERIFIED_INDICES_PATH" == "$RESULTS_NFS"/* ]]; then
    rel_verified="${GRASP_PRIOR_VERIFIED_INDICES_PATH#$RESULTS_NFS/}"
    GRASP_PRIOR_VERIFIED_INDICES_PATH="/results/$rel_verified"
    verified_indices_host="$RESULTS_NFS/$rel_verified"
  fi
fi

stable_pose_host=""
if [ -n "$OBJECT_STABLE_POSE_CACHE_DIR" ]; then
  if [[ "$OBJECT_STABLE_POSE_CACHE_DIR" == /results/* ]]; then
    stable_pose_host="$RESULTS_NFS/${OBJECT_STABLE_POSE_CACHE_DIR#/results/}"
  elif [[ "$OBJECT_STABLE_POSE_CACHE_DIR" == "$RESULTS_NFS"/* ]]; then
    rel_stable_pose="${OBJECT_STABLE_POSE_CACHE_DIR#$RESULTS_NFS/}"
    OBJECT_STABLE_POSE_CACHE_DIR="/results/$rel_stable_pose"
    stable_pose_host="$RESULTS_NFS/$rel_stable_pose"
  fi
fi

prior_host=""
if [ -n "$GRASP_PRIOR_LIBRARY_DIR" ]; then
  if [[ "$GRASP_PRIOR_LIBRARY_DIR" == /results/* ]]; then
    prior_host="$RESULTS_NFS/${GRASP_PRIOR_LIBRARY_DIR#/results/}"
  elif [[ "$GRASP_PRIOR_LIBRARY_DIR" == "$RESULTS_NFS"/* ]]; then
    rel_prior="${GRASP_PRIOR_LIBRARY_DIR#$RESULTS_NFS/}"
    GRASP_PRIOR_LIBRARY_DIR="/results/$rel_prior"
    prior_host="$RESULTS_NFS/$rel_prior"
  fi
fi

if [ ! -f "$IMAGE" ]; then
  echo "Missing Isaac Lab container image: $IMAGE"
  exit 2
fi
if [ ! -d "$ENV_ROOT/$ENV_NAME/site" ]; then
  echo "Missing DEXTRAH Python target: $ENV_ROOT/$ENV_NAME/site"
  exit 2
fi
if [ -n "$CHECKPOINT_HOST" ] && [ ! -f "$CHECKPOINT_HOST" ]; then
  echo "Missing checkpoint: $CHECKPOINT_HOST"
  exit 2
fi
if [ -n "$manifest_host" ] && [ ! -f "$manifest_host" ]; then
  echo "Missing object asset manifest: $manifest_host"
  exit 2
fi
case "$OBJECT_STABLE_POSE_ENABLED" in
  True|true|1|yes|Yes)
    if [ -z "$OBJECT_STABLE_POSE_CACHE_DIR" ]; then
      echo "OBJECT_STABLE_POSE_ENABLED=True requires OBJECT_STABLE_POSE_CACHE_DIR"
      exit 2
    fi
    if [ -n "$stable_pose_host" ] && [ ! -d "$stable_pose_host" ]; then
      echo "Missing stable-pose cache dir: $stable_pose_host"
      exit 2
    fi
    ;;
esac
case "$GRASP_PRIOR_RESET_ENABLED" in
  True|true|1|yes|Yes)
    if [ -n "$prior_host" ] && [ ! -d "$prior_host" ]; then
      echo "Missing grasp prior library dir: $prior_host"
      exit 2
    fi
    if [ -n "$verified_indices_host" ] && [ ! -f "$verified_indices_host" ]; then
      echo "Missing verified grasp indices: $verified_indices_host"
      exit 2
    fi
    ;;
esac

mkdir -p \
  "$RUN_DIR_HOST" \
  "$NFS_ROOT/slurm_logs/dextrah" \
  "$CACHE_NFS/kit" "$CACHE_NFS/ov" "$CACHE_NFS/pip" \
  "$CACHE_NFS/glcache" "$CACHE_NFS/computecache" \
  "$CACHE_NFS/omni_logs" "$CACHE_NFS/carb_logs" \
  "$CACHE_NFS/data" "$CACHE_NFS/documents"

export TASK RUN_NAME NUM_ENVS COLLECTION_STEPS TRAIN_STEPS BATCH_SIZE LEARNING_RATE WEIGHT_DECAY VALIDATION_FRACTION LOSS_DIMS EVAL_INTERVAL USE_CUDA_GRAPH SEED COLLECTION_ACTION_SOURCE ALLOW_DIAGNOSTIC_ACTION_SOURCES LABEL_ACTION_SOURCE COLLECTION_TEACHER_ALPHA COLLECTION_TEACHER_ALPHAS COLLECTION_REFERENCE_MIX_Z_ALPHA COLLECTION_REFERENCE_MIX_GRIPPER_ALPHA HOLD_TRIGGER_MODE HOLD_PHASE_START HOLD_TRIGGER_LIFT_HEIGHT HOLD_CONTACT_MAX_FINGER_DIST HOLD_LIFT_HEIGHT HOLD_TARGET_POLICY HOLD_GRIPPER_ACTION REHEARSAL_DATASET_PATHS REHEARSAL_DATASET_NAMES SOURCE_BATCH_MODE SOURCE_LOSS_WEIGHTS BEST_SCORE_WEIGHTS EARLY_STOP_PATIENCE DISTILL_SOURCES DISTILL_LOSS_WEIGHT DISTILL_DIMS RESIDUAL_ADAPTER_ENABLED RESIDUAL_HIDDEN_DIM RESIDUAL_MAX_ACTION RESIDUAL_PRESERVE_SOURCES RESIDUAL_PRESERVE_WEIGHT RESIDUAL_L2_WEIGHT RESIDUAL_GATE_ENABLED RESIDUAL_GATE_HIDDEN_DIM RESIDUAL_GATE_BIAS_INIT RESIDUAL_CONTEXT_FEATURES HANDOFF_SOURCE_ENABLED HANDOFF_SOURCE_SOURCES HANDOFF_SOURCE_NAME HANDOFF_TEACHER_ALPHA HANDOFF_MIN_PHASE HANDOFF_MAX_PHASE HANDOFF_MIN_LIFT_HEIGHT HANDOFF_MAX_FINGER_DIST HANDOFF_REQUIRE_HOLD_ACTIVE HANDOFF_REQUIRE_SUCCESS HANDOFF_REQUIRE_SAFE_TARGET HANDOFF_MAX_SAMPLES SOURCE_PROBE_STEPS SOURCE_PROBE_LR CUBE_SPAWN_XY_RANDOMIZATION TRAJECTORY_TRACKING_REFERENCE_PATH
export OBJECT_ASSET_MANIFEST_PATH OBJECT_ASSETS_DIR MAX_OBJECTS OBJECT_ASSET_ASSIGNMENT
export OBJECT_SPAWN_CENTER_OFFSET_X OBJECT_SPAWN_CENTER_OFFSET_Y OBJECT_SPAWN_XY_RANDOMIZATION
export OBJECT_SPAWN_YAW_RANDOMIZATION_DEG OBJECT_STABLE_POSE_ENABLED OBJECT_STABLE_POSE_CACHE_DIR
export OBJECT_STABLE_POSE_COUNT OBJECT_STABLE_POSE_RANDOMIZE OBJECT_STABLE_POSE_ALLOW_MISSING
export GRASP_PRIOR_RESET_ENABLED GRASP_PRIOR_LIBRARY_DIR GRASP_PRIOR_VERIFIED_INDICES_PATH GRASP_PRIOR_ALLOW_MISSING
export GRASP_PRIOR_RESET_ATTEMPTS GRASP_PRIOR_RESET_CANDIDATE_COUNT GRASP_PRIOR_RESET_REQUIRE_TOPDOWN
export GRASP_PRIOR_RESET_MIN_PREGRASP_Z GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC GRASP_PRIOR_RESET_MIN_WIDTH
export GRASP_PRIOR_RESET_IK_ITERATIONS GRASP_PRIOR_RESET_IK_DAMPING GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP
export GRASP_PRIOR_RESET_IK_POS_TOLERANCE GRASP_PRIOR_RESET_IK_ROT_TOLERANCE GRASP_PRIOR_PREGRASP_OFFSET
export GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS
export GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH
export GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN
export GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z
export GRASP_PRIOR_ACTION_WARMSTART_GAIN GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION
export GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR
export GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST
export GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN
export CHECKPOINT_ARG RUN_DIR_CONTAINER BC_CHECKPOINT_CONTAINER DATASET_CONTAINER ENV_NAME

echo "Running DextrAH Franka cube trajectory BC diagnostic"
echo "SLURM_JOB_ID=$SLURM_JOB_ID_SAFE"
echo "SLURM_JOB_NODELIST=${SLURM_JOB_NODELIST:-unset}"
echo "IMAGE=$IMAGE"
echo "CODE_NFS=$CODE_NFS"
echo "FABRICS_NFS=$FABRICS_NFS"
echo "ISAACLAB_NFS=$ISAACLAB_NFS"
echo "RESULTS_NFS=$RESULTS_NFS"
echo "TASK=$TASK"
echo "RUN_NAME=$RUN_NAME"
echo "NUM_ENVS=$NUM_ENVS"
echo "COLLECTION_STEPS=$COLLECTION_STEPS"
echo "TRAIN_STEPS=$TRAIN_STEPS"
echo "BATCH_SIZE=$BATCH_SIZE"
echo "LEARNING_RATE=$LEARNING_RATE"
echo "WEIGHT_DECAY=$WEIGHT_DECAY"
echo "VALIDATION_FRACTION=$VALIDATION_FRACTION"
echo "LOSS_DIMS=$LOSS_DIMS"
echo "EVAL_INTERVAL=$EVAL_INTERVAL"
echo "USE_CUDA_GRAPH=$USE_CUDA_GRAPH"
echo "SEED=$SEED"
echo "COLLECTION_ACTION_SOURCE=$COLLECTION_ACTION_SOURCE"
echo "ALLOW_DIAGNOSTIC_ACTION_SOURCES=$ALLOW_DIAGNOSTIC_ACTION_SOURCES"
echo "LABEL_ACTION_SOURCE=$LABEL_ACTION_SOURCE"
echo "COLLECTION_TEACHER_ALPHA=$COLLECTION_TEACHER_ALPHA"
echo "COLLECTION_TEACHER_ALPHAS=$COLLECTION_TEACHER_ALPHAS"
echo "COLLECTION_REFERENCE_MIX_Z_ALPHA=$COLLECTION_REFERENCE_MIX_Z_ALPHA"
echo "COLLECTION_REFERENCE_MIX_GRIPPER_ALPHA=$COLLECTION_REFERENCE_MIX_GRIPPER_ALPHA"
echo "HOLD_TRIGGER_MODE=$HOLD_TRIGGER_MODE"
echo "HOLD_PHASE_START=$HOLD_PHASE_START"
echo "HOLD_TRIGGER_LIFT_HEIGHT=$HOLD_TRIGGER_LIFT_HEIGHT"
echo "HOLD_CONTACT_MAX_FINGER_DIST=$HOLD_CONTACT_MAX_FINGER_DIST"
echo "HOLD_LIFT_HEIGHT=$HOLD_LIFT_HEIGHT"
echo "HOLD_TARGET_POLICY=$HOLD_TARGET_POLICY"
echo "HOLD_GRIPPER_ACTION=$HOLD_GRIPPER_ACTION"
echo "REHEARSAL_DATASET_PATHS=$REHEARSAL_DATASET_PATHS"
echo "REHEARSAL_DATASET_NAMES=$REHEARSAL_DATASET_NAMES"
echo "SOURCE_BATCH_MODE=$SOURCE_BATCH_MODE"
echo "SOURCE_LOSS_WEIGHTS=$SOURCE_LOSS_WEIGHTS"
echo "BEST_SCORE_WEIGHTS=$BEST_SCORE_WEIGHTS"
echo "EARLY_STOP_PATIENCE=$EARLY_STOP_PATIENCE"
echo "DISTILL_SOURCES=$DISTILL_SOURCES"
echo "DISTILL_LOSS_WEIGHT=$DISTILL_LOSS_WEIGHT"
echo "DISTILL_DIMS=$DISTILL_DIMS"
echo "RESIDUAL_ADAPTER_ENABLED=$RESIDUAL_ADAPTER_ENABLED"
echo "RESIDUAL_HIDDEN_DIM=$RESIDUAL_HIDDEN_DIM"
echo "RESIDUAL_MAX_ACTION=$RESIDUAL_MAX_ACTION"
echo "RESIDUAL_PRESERVE_SOURCES=$RESIDUAL_PRESERVE_SOURCES"
echo "RESIDUAL_PRESERVE_WEIGHT=$RESIDUAL_PRESERVE_WEIGHT"
echo "RESIDUAL_L2_WEIGHT=$RESIDUAL_L2_WEIGHT"
echo "RESIDUAL_GATE_ENABLED=$RESIDUAL_GATE_ENABLED"
echo "RESIDUAL_GATE_HIDDEN_DIM=$RESIDUAL_GATE_HIDDEN_DIM"
echo "RESIDUAL_GATE_BIAS_INIT=$RESIDUAL_GATE_BIAS_INIT"
echo "RESIDUAL_CONTEXT_FEATURES=$RESIDUAL_CONTEXT_FEATURES"
echo "HANDOFF_SOURCE_ENABLED=$HANDOFF_SOURCE_ENABLED"
echo "HANDOFF_SOURCE_SOURCES=$HANDOFF_SOURCE_SOURCES"
echo "HANDOFF_SOURCE_NAME=$HANDOFF_SOURCE_NAME"
echo "HANDOFF_TEACHER_ALPHA=$HANDOFF_TEACHER_ALPHA"
echo "HANDOFF_MIN_PHASE=$HANDOFF_MIN_PHASE"
echo "HANDOFF_MAX_PHASE=$HANDOFF_MAX_PHASE"
echo "HANDOFF_MIN_LIFT_HEIGHT=$HANDOFF_MIN_LIFT_HEIGHT"
echo "HANDOFF_MAX_FINGER_DIST=$HANDOFF_MAX_FINGER_DIST"
echo "HANDOFF_REQUIRE_HOLD_ACTIVE=$HANDOFF_REQUIRE_HOLD_ACTIVE"
echo "HANDOFF_REQUIRE_SUCCESS=$HANDOFF_REQUIRE_SUCCESS"
echo "HANDOFF_REQUIRE_SAFE_TARGET=$HANDOFF_REQUIRE_SAFE_TARGET"
echo "HANDOFF_MAX_SAMPLES=$HANDOFF_MAX_SAMPLES"
echo "SOURCE_PROBE_STEPS=$SOURCE_PROBE_STEPS"
echo "SOURCE_PROBE_LR=$SOURCE_PROBE_LR"
echo "CUBE_SPAWN_XY_RANDOMIZATION=$CUBE_SPAWN_XY_RANDOMIZATION"
echo "TRAJECTORY_TRACKING_REFERENCE_PATH=$TRAJECTORY_TRACKING_REFERENCE_PATH"
echo "OBJECT_ASSET_MANIFEST_PATH=$OBJECT_ASSET_MANIFEST_PATH"
echo "OBJECT_ASSETS_DIR=$OBJECT_ASSETS_DIR"
echo "MAX_OBJECTS=$MAX_OBJECTS"
echo "OBJECT_ASSET_ASSIGNMENT=$OBJECT_ASSET_ASSIGNMENT"
echo "OBJECT_SPAWN_CENTER_OFFSET_X=$OBJECT_SPAWN_CENTER_OFFSET_X"
echo "OBJECT_SPAWN_CENTER_OFFSET_Y=$OBJECT_SPAWN_CENTER_OFFSET_Y"
echo "OBJECT_SPAWN_XY_RANDOMIZATION=$OBJECT_SPAWN_XY_RANDOMIZATION"
echo "OBJECT_SPAWN_YAW_RANDOMIZATION_DEG=$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
echo "OBJECT_STABLE_POSE_ENABLED=$OBJECT_STABLE_POSE_ENABLED"
echo "OBJECT_STABLE_POSE_CACHE_DIR=$OBJECT_STABLE_POSE_CACHE_DIR"
echo "OBJECT_STABLE_POSE_COUNT=$OBJECT_STABLE_POSE_COUNT"
echo "OBJECT_STABLE_POSE_RANDOMIZE=$OBJECT_STABLE_POSE_RANDOMIZE"
echo "OBJECT_STABLE_POSE_ALLOW_MISSING=$OBJECT_STABLE_POSE_ALLOW_MISSING"
echo "GRASP_PRIOR_RESET_ENABLED=$GRASP_PRIOR_RESET_ENABLED"
echo "GRASP_PRIOR_LIBRARY_DIR=$GRASP_PRIOR_LIBRARY_DIR"
echo "GRASP_PRIOR_VERIFIED_INDICES_PATH=$GRASP_PRIOR_VERIFIED_INDICES_PATH"
echo "GRASP_PRIOR_ALLOW_MISSING=$GRASP_PRIOR_ALLOW_MISSING"
echo "GRASP_PRIOR_RESET_ATTEMPTS=$GRASP_PRIOR_RESET_ATTEMPTS"
echo "GRASP_PRIOR_RESET_CANDIDATE_COUNT=$GRASP_PRIOR_RESET_CANDIDATE_COUNT"
echo "GRASP_PRIOR_RESET_REQUIRE_TOPDOWN=$GRASP_PRIOR_RESET_REQUIRE_TOPDOWN"
echo "GRASP_PRIOR_RESET_MIN_PREGRASP_Z=$GRASP_PRIOR_RESET_MIN_PREGRASP_Z"
echo "GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC=$GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC"
echo "GRASP_PRIOR_RESET_MIN_WIDTH=$GRASP_PRIOR_RESET_MIN_WIDTH"
echo "GRASP_PRIOR_RESET_IK_ITERATIONS=$GRASP_PRIOR_RESET_IK_ITERATIONS"
echo "GRASP_PRIOR_RESET_IK_DAMPING=$GRASP_PRIOR_RESET_IK_DAMPING"
echo "GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP=$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP"
echo "GRASP_PRIOR_RESET_IK_POS_TOLERANCE=$GRASP_PRIOR_RESET_IK_POS_TOLERANCE"
echo "GRASP_PRIOR_RESET_IK_ROT_TOLERANCE=$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE"
echo "GRASP_PRIOR_PREGRASP_OFFSET=$GRASP_PRIOR_PREGRASP_OFFSET"
echo "GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS=$GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS"
echo "GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS=$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS"
echo "GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH=$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH"
echo "GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH=$GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH"
echo "GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN=$GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
echo "GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH=$GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z"
echo "GRASP_PRIOR_ACTION_WARMSTART_GAIN=$GRASP_PRIOR_ACTION_WARMSTART_GAIN"
echo "GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION=$GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION"
echo "GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION=$GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION"
echo "GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR=$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
echo "GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN=$GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
echo "CHECKPOINT_ARG=$CHECKPOINT_ARG"
echo "CHECKPOINT_HOST=$CHECKPOINT_HOST"
echo "RUN_DIR_HOST=$RUN_DIR_HOST"
echo "BC_CHECKPOINT_CONTAINER=$BC_CHECKPOINT_CONTAINER"
echo "DATASET_CONTAINER=$DATASET_CONTAINER"

srun \
  --ntasks=1 \
  --container-image="$IMAGE" \
  --container-mounts=/dev/shm:/dev/shm,"$CODE_NFS":/code,"$FABRICS_NFS":/fabrics,"$ISAACLAB_NFS":/IsaacLab,"$ENV_ROOT":/envs,"$RESULTS_NFS":/results,"$CACHE_NFS/kit":/isaac-sim/kit/cache,"$CACHE_NFS/ov":/root/.cache/ov,"$CACHE_NFS/pip":/root/.cache/pip,"$CACHE_NFS/glcache":/root/.cache/nvidia/GLCache,"$CACHE_NFS/computecache":/root/.nv/ComputeCache,"$CACHE_NFS/omni_logs":/root/.nvidia-omniverse/logs,"$CACHE_NFS/carb_logs":/isaac-sim/kit/logs/Kit/Isaac-Sim,"$CACHE_NFS/data":/root/.local/share/ov/data,"$CACHE_NFS/documents":/root/Documents \
  --no-container-entrypoint \
  --container-remap-root \
  --container-writable \
  --export=ALL,PYTHONUNBUFFERED=1,HYDRA_FULL_ERROR=1,PYTHONFAULTHANDLER=1,TORCH_SHOW_CPP_STACKTRACES=1,ACCEPT_EULA=Y,PRIVACY_CONSENT=Y \
  bash -lc '
    set -euo pipefail
    export SITE="/envs/$ENV_NAME/site"
    export PYTHONPATH="$SITE:/code:/fabrics/src"
    for d in /IsaacLab/source/*; do
      if [ -d "$d" ]; then
        export PYTHONPATH="$d:$PYTHONPATH"
      fi
    done
    export WANDB_MODE=offline
    mkdir -p "$RUN_DIR_CONTAINER" /results/logs

    cd /code
    echo "container_host=$(hostname)"
    echo "container_cuda_visible_devices=${CUDA_VISIBLE_DEVICES:-unset}"
    git rev-parse HEAD || true
    echo "git_status_skipped=container_git_lfs_unavailable"
    nvidia-smi || true

    cd /code/dextrah_lab/rl_games

    TASK_OVERRIDES=(
      agent.wandb_activate=False
      env.use_cuda_graph="$USE_CUDA_GRAPH"
    )
    if [ "$TASK" = "Dextrah-Franka-Multi-Object-Grasp" ] || [ "$TASK" = "Dextrah-Franka-Multi-Object-RGB-Grasp" ]; then
      TASK_OVERRIDES+=(
        env.max_objects="$MAX_OBJECTS"
        env.object_asset_assignment="$OBJECT_ASSET_ASSIGNMENT"
        env.object_spawn_center_offset_x="$OBJECT_SPAWN_CENTER_OFFSET_X"
        env.object_spawn_center_offset_y="$OBJECT_SPAWN_CENTER_OFFSET_Y"
        env.object_spawn_xy_randomization="$OBJECT_SPAWN_XY_RANDOMIZATION"
        env.object_spawn_yaw_randomization_deg="$OBJECT_SPAWN_YAW_RANDOMIZATION_DEG"
        env.object_stable_pose_enabled="$OBJECT_STABLE_POSE_ENABLED"
        env.object_stable_pose_count="$OBJECT_STABLE_POSE_COUNT"
        env.object_stable_pose_randomize="$OBJECT_STABLE_POSE_RANDOMIZE"
        env.object_stable_pose_allow_missing="$OBJECT_STABLE_POSE_ALLOW_MISSING"
      )
      if [ -n "$OBJECT_ASSET_MANIFEST_PATH" ]; then
        TASK_OVERRIDES+=(env.object_asset_manifest_path="$OBJECT_ASSET_MANIFEST_PATH")
      fi
      if [ -n "$OBJECT_ASSETS_DIR" ]; then
        TASK_OVERRIDES+=(env.object_assets_dir="$OBJECT_ASSETS_DIR")
      fi
      if [ -n "$OBJECT_STABLE_POSE_CACHE_DIR" ]; then
        TASK_OVERRIDES+=(env.object_stable_pose_cache_dir="$OBJECT_STABLE_POSE_CACHE_DIR")
      fi
      case "$GRASP_PRIOR_RESET_ENABLED" in
        True|true|1|yes|Yes)
          TASK_OVERRIDES+=(
            env.grasp_prior_reset_enabled=True
            env.grasp_prior_allow_missing="$GRASP_PRIOR_ALLOW_MISSING"
            env.grasp_prior_reset_attempts="$GRASP_PRIOR_RESET_ATTEMPTS"
            env.grasp_prior_reset_candidate_count="$GRASP_PRIOR_RESET_CANDIDATE_COUNT"
            env.grasp_prior_reset_require_topdown="$GRASP_PRIOR_RESET_REQUIRE_TOPDOWN"
            env.grasp_prior_reset_min_pregrasp_z="$GRASP_PRIOR_RESET_MIN_PREGRASP_Z"
            env.grasp_prior_reset_max_center_distance_frac="$GRASP_PRIOR_RESET_MAX_CENTER_DISTANCE_FRAC"
            env.grasp_prior_reset_min_width="$GRASP_PRIOR_RESET_MIN_WIDTH"
            env.grasp_prior_action_warmstart_approach_steps="$GRASP_PRIOR_ACTION_WARMSTART_APPROACH_STEPS"
            env.grasp_prior_action_warmstart_close_steps="$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_STEPS"
            env.grasp_prior_action_warmstart_lift_steps="$GRASP_PRIOR_ACTION_WARMSTART_LIFT_STEPS"
            env.grasp_prior_action_warmstart_close_width="$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_WIDTH"
            env.grasp_prior_action_warmstart_use_prior_close_width="$GRASP_PRIOR_ACTION_WARMSTART_USE_PRIOR_CLOSE_WIDTH"
            env.grasp_prior_action_warmstart_prior_close_width_margin="$GRASP_PRIOR_ACTION_WARMSTART_PRIOR_CLOSE_WIDTH_MARGIN"
            env.grasp_prior_action_warmstart_min_close_width="$GRASP_PRIOR_ACTION_WARMSTART_MIN_CLOSE_WIDTH"
            env.grasp_prior_action_warmstart_lift_action_z="$GRASP_PRIOR_ACTION_WARMSTART_LIFT_ACTION_Z"
            env.grasp_prior_action_warmstart_gain="$GRASP_PRIOR_ACTION_WARMSTART_GAIN"
            env.grasp_prior_action_warmstart_max_position_action="$GRASP_PRIOR_ACTION_WARMSTART_MAX_POSITION_ACTION"
            env.grasp_prior_action_warmstart_track_orientation="$GRASP_PRIOR_ACTION_WARMSTART_TRACK_ORIENTATION"
            env.grasp_prior_action_warmstart_close_max_ee_error="$GRASP_PRIOR_ACTION_WARMSTART_CLOSE_MAX_EE_ERROR"
            env.grasp_prior_action_warmstart_lift_max_ee_error="$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_EE_ERROR"
            env.grasp_prior_action_warmstart_lift_max_finger_center_dist="$GRASP_PRIOR_ACTION_WARMSTART_LIFT_MAX_FINGER_CENTER_DIST"
            env.grasp_prior_action_warmstart_lift_closed_width_margin="$GRASP_PRIOR_ACTION_WARMSTART_LIFT_CLOSED_WIDTH_MARGIN"
          )
          if [ -n "$GRASP_PRIOR_LIBRARY_DIR" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_library_dir="$GRASP_PRIOR_LIBRARY_DIR")
          fi
          if [ -n "$GRASP_PRIOR_VERIFIED_INDICES_PATH" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_verified_indices_path="$GRASP_PRIOR_VERIFIED_INDICES_PATH")
          fi
          if [ -n "$GRASP_PRIOR_PREGRASP_OFFSET" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_pregrasp_offset="$GRASP_PRIOR_PREGRASP_OFFSET")
          fi
          if [ -n "$GRASP_PRIOR_RESET_IK_ITERATIONS" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_reset_ik_iterations="$GRASP_PRIOR_RESET_IK_ITERATIONS")
          fi
          if [ -n "$GRASP_PRIOR_RESET_IK_DAMPING" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_reset_ik_damping="$GRASP_PRIOR_RESET_IK_DAMPING")
          fi
          if [ -n "$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_reset_ik_max_joint_step="$GRASP_PRIOR_RESET_IK_MAX_JOINT_STEP")
          fi
          if [ -n "$GRASP_PRIOR_RESET_IK_POS_TOLERANCE" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_reset_ik_pos_tolerance="$GRASP_PRIOR_RESET_IK_POS_TOLERANCE")
          fi
          if [ -n "$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE" ]; then
            TASK_OVERRIDES+=(env.grasp_prior_reset_ik_rot_tolerance="$GRASP_PRIOR_RESET_IK_ROT_TOLERANCE")
          fi
          ;;
      esac
    else
      TASK_OVERRIDES+=(
        env.cube_spawn_xy_randomization="$CUBE_SPAWN_XY_RANDOMIZATION"
        env.trajectory_tracking_teacher_force_enabled=False
      )
      if [ -n "$TRAJECTORY_TRACKING_REFERENCE_PATH" ]; then
        TASK_OVERRIDES+=(
          env.trajectory_tracking_reference_path="$TRAJECTORY_TRACKING_REFERENCE_PATH"
        )
      fi
    fi

    BC_ARGS=(
      bc_reference_action_imitation.py
      --headless
      --task="$TASK"
      --num_envs "$NUM_ENVS"
      --collection_steps "$COLLECTION_STEPS"
      --train_steps "$TRAIN_STEPS"
      --batch_size "$BATCH_SIZE"
      --learning_rate "$LEARNING_RATE"
      --weight_decay "$WEIGHT_DECAY"
      --validation_fraction "$VALIDATION_FRACTION"
      --loss_dims "$LOSS_DIMS"
      --eval_interval "$EVAL_INTERVAL"
      --seed "$SEED"
      --collection_action_source "$COLLECTION_ACTION_SOURCE"
      --label_action_source "$LABEL_ACTION_SOURCE"
      --collection_teacher_alpha "$COLLECTION_TEACHER_ALPHA"
      --collection_teacher_alphas "$COLLECTION_TEACHER_ALPHAS"
      --collection_reference_mix_z_alpha "$COLLECTION_REFERENCE_MIX_Z_ALPHA"
      --collection_reference_mix_gripper_alpha "$COLLECTION_REFERENCE_MIX_GRIPPER_ALPHA"
      --hold_trigger_mode "$HOLD_TRIGGER_MODE"
      --hold_phase_start "$HOLD_PHASE_START"
      --hold_trigger_lift_height "$HOLD_TRIGGER_LIFT_HEIGHT"
      --hold_contact_max_finger_dist "$HOLD_CONTACT_MAX_FINGER_DIST"
      --hold_lift_height "$HOLD_LIFT_HEIGHT"
      --hold_target_policy "$HOLD_TARGET_POLICY"
      --hold_gripper_action "$HOLD_GRIPPER_ACTION"
      --rehearsal_dataset_paths "$REHEARSAL_DATASET_PATHS"
      --rehearsal_dataset_names "$REHEARSAL_DATASET_NAMES"
      --source_batch_mode "$SOURCE_BATCH_MODE"
      --source_loss_weights "$SOURCE_LOSS_WEIGHTS"
      --best_score_weights "$BEST_SCORE_WEIGHTS"
      --early_stop_patience "$EARLY_STOP_PATIENCE"
      --distill_sources "$DISTILL_SOURCES"
      --distill_loss_weight "$DISTILL_LOSS_WEIGHT"
      --distill_dims "$DISTILL_DIMS"
      --residual_adapter_enabled "$RESIDUAL_ADAPTER_ENABLED"
      --residual_hidden_dim "$RESIDUAL_HIDDEN_DIM"
      --residual_max_action "$RESIDUAL_MAX_ACTION"
      --residual_preserve_sources "$RESIDUAL_PRESERVE_SOURCES"
      --residual_preserve_weight "$RESIDUAL_PRESERVE_WEIGHT"
      --residual_l2_weight "$RESIDUAL_L2_WEIGHT"
      --residual_gate_enabled "$RESIDUAL_GATE_ENABLED"
      --residual_gate_hidden_dim "$RESIDUAL_GATE_HIDDEN_DIM"
      --residual_gate_bias_init "$RESIDUAL_GATE_BIAS_INIT"
      --residual_context_features "$RESIDUAL_CONTEXT_FEATURES"
      --handoff_source_enabled "$HANDOFF_SOURCE_ENABLED"
      --handoff_source_sources "$HANDOFF_SOURCE_SOURCES"
      --handoff_source_name "$HANDOFF_SOURCE_NAME"
      --handoff_teacher_alpha "$HANDOFF_TEACHER_ALPHA"
      --handoff_min_phase "$HANDOFF_MIN_PHASE"
      --handoff_max_phase "$HANDOFF_MAX_PHASE"
      --handoff_min_lift_height "$HANDOFF_MIN_LIFT_HEIGHT"
      --handoff_max_finger_dist "$HANDOFF_MAX_FINGER_DIST"
      --handoff_require_hold_active "$HANDOFF_REQUIRE_HOLD_ACTIVE"
      --handoff_require_success "$HANDOFF_REQUIRE_SUCCESS"
      --handoff_require_safe_target "$HANDOFF_REQUIRE_SAFE_TARGET"
      --handoff_max_samples "$HANDOFF_MAX_SAMPLES"
      --source_probe_steps "$SOURCE_PROBE_STEPS"
      --source_probe_lr "$SOURCE_PROBE_LR"
      --output_dir "$RUN_DIR_CONTAINER"
      --dataset_path "$DATASET_CONTAINER"
      --bc_checkpoint_path "$BC_CHECKPOINT_CONTAINER"
      --checkpoint "$CHECKPOINT_ARG"
      "${TASK_OVERRIDES[@]}"
    )

    printf "bc_command="
    printf "%q " /isaac-sim/python.sh "${BC_ARGS[@]}"
    printf "\n"
    /isaac-sim/python.sh "${BC_ARGS[@]}"
  '

if [ -f "$LOG_FILE" ] && grep -E "Traceback|RuntimeError:|Error executing job with overrides|ChildFailedError|Could not execute <function load" "$LOG_FILE" >/dev/null; then
  echo "Detected BC diagnostic error patterns in $LOG_FILE."
  exit 1
fi

if [ ! -s "$RUN_DIR_HOST/bc_metrics.json" ]; then
  echo "Missing BC metrics JSON: $RUN_DIR_HOST/bc_metrics.json"
  exit 1
fi
if [ ! -s "$RUN_DIR_HOST/nn/bc_reference_action_imitation.pth" ]; then
  echo "Missing BC checkpoint: $RUN_DIR_HOST/nn/bc_reference_action_imitation.pth"
  exit 1
fi

echo "BC Diagnostic Done"
