#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --account=nvr_lpr_rvp
#SBATCH --gpus-per-node=1
#SBATCH --job-name=yam_policy_demo
#SBATCH --partition=batch_singlenode,grizzly,polar,polar3,polar4,interactive_singlenode
#SBATCH --time=0-03:50:00
#SBATCH --mem=160G
#SBATCH --cpus-per-task=16
#SBATCH --output=/lustre/fsw/portfolios/nvr/users/lzha/slurm_logs/dextrah/yam_policy_demo_%j.out

set -euo pipefail

NFS_ROOT="${NFS_ROOT:-/lustre/fsw/portfolios/nvr/users/lzha}"
CODE_NFS="${CODE_NFS:-$NFS_ROOT/src/DEXTRAH}"
RESULTS_NFS="${RESULTS_NFS:-$NFS_ROOT/results/dextrah}"

export NFS_ROOT CODE_NFS RESULTS_NFS

# Coordinate convention: Y is the long/right-left table axis.  Robot right is
# -Y, robot left is +Y, and the YAM forward/back direction is X.
export TOTAL_TARGET="${TOTAL_TARGET:-500}"
export BATCH_NAME="${BATCH_NAME:-yam_single_object_policy_500_$(date -u +%Y%m%dT%H%M%SZ)}"
export BATCH_DIR="${BATCH_DIR:-$RESULTS_NFS/yam_demos/$BATCH_NAME}"
export OBJECTS_PER_DEMO="${OBJECTS_PER_DEMO:-1}"
export OBJECTS_PER_DEMO_MIN="${OBJECTS_PER_DEMO_MIN:-1}"
export OBJECTS_PER_DEMO_MAX="${OBJECTS_PER_DEMO_MAX:-1}"

export SETTLE_STEPS="${SETTLE_STEPS:-100}"
export SETTLE_CAPTURE_INTERVAL="${SETTLE_CAPTURE_INTERVAL:-20}"
export REPLAY_CAPTURE_INTERVAL="${REPLAY_CAPTURE_INTERVAL:-10}"
export FPS="${FPS:-12}"
export RECORD_RGB_WIDTH="${RECORD_RGB_WIDTH:-160}"
export RECORD_RGB_HEIGHT="${RECORD_RGB_HEIGHT:-120}"
export RECORD_RGB_INTERVAL="${RECORD_RGB_INTERVAL:-4}"
export RECORD_MULTICAM_RGB="${RECORD_MULTICAM_RGB:-False}"
export RECORD_SCENE_RGB="${RECORD_SCENE_RGB:-True}"
export RECORD_WRIST_RGB="${RECORD_WRIST_RGB:-False}"
export RENDERING_MODE="${RENDERING_MODE:-balanced}"

export DEMO_STEPS_PER_OBJECT="${DEMO_STEPS_PER_OBJECT:-900}"
export MAX_ATTEMPTS="${MAX_ATTEMPTS:-180}"
export NUM_GRASPS="${NUM_GRASPS:-192}"
export TOPK="${TOPK:-96}"
export MAX_PLAN_ATTEMPTS="${MAX_PLAN_ATTEMPTS:-96}"
export YAM_GRASP_FILTER_MIN_KEEP="${YAM_GRASP_FILTER_MIN_KEEP:-4}"
export YAM_ALLOW_LIFT_FILTER_FALLBACK="${YAM_ALLOW_LIFT_FILTER_FALLBACK:-False}"
export POOL_MAX_ASSETS="${POOL_MAX_ASSETS:-512}"
export POOL_MAX_XY_RADIUS="${POOL_MAX_XY_RADIUS:-0.055}"
export POOL_MAX_GRASP_WIDTH_P95="${POOL_MAX_GRASP_WIDTH_P95:-0.110}"
export POOL_MIN_XY_HALF_EXTENT="${POOL_MIN_XY_HALF_EXTENT:-0.020}"
export POOL_MIN_Z_HALF_EXTENT="${POOL_MIN_Z_HALF_EXTENT:-0.032}"
export POOL_MAX_XY_ASPECT="${POOL_MAX_XY_ASPECT:-1.8}"

# Keep the generated motion more continuous than the earlier visualization
# demos while retaining enough samples through lift/transport/drop.
export SCRIPTED_LIFT_HEIGHT="${SCRIPTED_LIFT_HEIGHT:-0.13}"
export SCRIPTED_LIFT_FRAMES="${SCRIPTED_LIFT_FRAMES:-120}"
export MOVE_TO_BIN_FRAMES="${MOVE_TO_BIN_FRAMES:-220}"
export START_GUARD_FRAMES="${START_GUARD_FRAMES:-12}"
export CLOSE_FRAMES="${CLOSE_FRAMES:-36}"
export HOLD_FRAMES="${HOLD_FRAMES:-12}"
export HOLD_AFTER_CLOSE_FRAMES="${HOLD_AFTER_CLOSE_FRAMES:-24}"
export RETURN_TO_START_FRAMES="${RETURN_TO_START_FRAMES:-60}"
export DROP_HEIGHT_ABOVE_BIN="${DROP_HEIGHT_ABOVE_BIN:-0.14}"
export SCRIPTED_BIN_DROP_Y_OFFSET="${SCRIPTED_BIN_DROP_Y_OFFSET:-0.0}"
export SCRIPTED_BIN_DROP_Y_OFFSET_AFTER_FIRST="${SCRIPTED_BIN_DROP_Y_OFFSET_AFTER_FIRST:-0.0}"

export OBJECT_SPAWN_XY_RANDOMIZATION="${OBJECT_SPAWN_XY_RANDOMIZATION:-0.0}"
export TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION="${TABLETOP_CLUTTER_SPAWN_XY_RANDOMIZATION:-0.0}"
export TABLETOP_CLUTTER_MAX_OBJECTS="${TABLETOP_CLUTTER_MAX_OBJECTS:-0}"
export TABLETOP_CLUTTER_OBJECT_COUNT="${TABLETOP_CLUTTER_OBJECT_COUNT:-0}"
export TABLETOP_CLUTTER_ASSET_ASSIGNMENT="${TABLETOP_CLUTTER_ASSET_ASSIGNMENT:-random_without_replacement}"
export OBJECT_ASSET_ASSIGNMENT="${OBJECT_ASSET_ASSIGNMENT:-random}"

export YAM_POLICY_SCENE_RANDOMIZATION="${YAM_POLICY_SCENE_RANDOMIZATION:-True}"
export YAM_POLICY_OBJECT_X_RANGE="${YAM_POLICY_OBJECT_X_RANGE:--0.34 -0.24}"
export YAM_POLICY_OBJECT_Y_RANGE="${YAM_POLICY_OBJECT_Y_RANGE:--0.34 -0.22}"
export YAM_POLICY_BIN_X_RANGE="${YAM_POLICY_BIN_X_RANGE:--0.34 -0.10}"
export YAM_POLICY_BIN_Y_RANGE="${YAM_POLICY_BIN_Y_RANGE:-0.08 0.30}"
export YAM_POLICY_BIN_INNER_SIZE_X_RANGE="${YAM_POLICY_BIN_INNER_SIZE_X_RANGE:-0.28 0.42}"
export YAM_POLICY_BIN_INNER_SIZE_Y_RANGE="${YAM_POLICY_BIN_INNER_SIZE_Y_RANGE:-0.20 0.34}"
export YAM_POLICY_BIN_WALL_HEIGHT_RANGE="${YAM_POLICY_BIN_WALL_HEIGHT_RANGE:-0.08 0.16}"
export YAM_POLICY_SCENE_CAMERA_EYE_JITTER="${YAM_POLICY_SCENE_CAMERA_EYE_JITTER:-0.05 0.07 0.05}"
export YAM_POLICY_SCENE_CAMERA_TARGET_JITTER="${YAM_POLICY_SCENE_CAMERA_TARGET_JITTER:-0.04 0.05 0.03}"
export YAM_POLICY_DOME_LIGHT_INTENSITY_RANGE="${YAM_POLICY_DOME_LIGHT_INTENSITY_RANGE:-450 1600}"
export YAM_POLICY_KEY_LIGHT_INTENSITY_RANGE="${YAM_POLICY_KEY_LIGHT_INTENSITY_RANGE:-250 1400}"
export YAM_POLICY_MATERIAL_VALUE_RANGE="${YAM_POLICY_MATERIAL_VALUE_RANGE:-0.32 0.82}"

echo "Launching single-object YAM policy demo collection through shared collector"
echo "BATCH_NAME=$BATCH_NAME"
echo "BATCH_DIR=$BATCH_DIR"
echo "TOTAL_TARGET=$TOTAL_TARGET"
echo "OBJECT_X_RANGE=$YAM_POLICY_OBJECT_X_RANGE"
echo "OBJECT_Y_RANGE=$YAM_POLICY_OBJECT_Y_RANGE"
echo "BIN_Y_RANGE=$YAM_POLICY_BIN_Y_RANGE"
echo "POOL_MAX_ASSETS=$POOL_MAX_ASSETS"
echo "POOL_MAX_XY_RADIUS=$POOL_MAX_XY_RADIUS"
echo "POOL_MAX_GRASP_WIDTH_P95=$POOL_MAX_GRASP_WIDTH_P95"
echo "POOL_MIN_XY_HALF_EXTENT=$POOL_MIN_XY_HALF_EXTENT"
echo "POOL_MIN_Z_HALF_EXTENT=$POOL_MIN_Z_HALF_EXTENT"
echo "POOL_MAX_XY_ASPECT=$POOL_MAX_XY_ASPECT"
echo "MAX_ATTEMPTS=$MAX_ATTEMPTS"
echo "MOTION_TIMING=start_guard:$START_GUARD_FRAMES close:$CLOSE_FRAMES hold:$HOLD_FRAMES after_close:$HOLD_AFTER_CLOSE_FRAMES lift:$SCRIPTED_LIFT_FRAMES bin:$MOVE_TO_BIN_FRAMES return:$RETURN_TO_START_FRAMES"

exec bash "$CODE_NFS/cluster/sbatch_collect_yam_objaverse_demos_1gpu.sh"
