"""Build explicit SPEC_N entries for Franka cube contact-relabel jobs.

The contact relabel Slurm wrapper accepts episode specifications through
``SPEC_COUNT`` and ``SPEC_N`` environment variables.  This helper derives those
entries from the source metadata written by ``trajectory_conversion.py`` so the
job does not rely on brittle trajectory path templates.
"""

from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path
from typing import Any


def _container_path(
    path: str,
    *,
    local_curobo_root: Path,
    container_curobo_root: str,
) -> str:
    raw = Path(path)
    if path.startswith("/results/"):
        return path
    try:
        rel = raw.resolve().relative_to(local_curobo_root.resolve())
    except ValueError:
        parts = raw.parts
        if "curobo_plans" not in parts:
            raise ValueError(
                f"Cannot map source trajectory path to container path: {path}. "
                "Pass --local-curobo-root or use metadata paths under a curobo_plans directory."
            )
        idx = parts.index("curobo_plans")
        rel = Path(*parts[idx + 1 :])
    return str(Path(container_curobo_root) / rel)


def _selected_episode_indices(num_sources: int, episodes: list[int] | None, limit: int | None) -> list[int]:
    if episodes:
        selected = [int(ep) for ep in episodes]
    else:
        selected = list(range(num_sources))
    if limit is not None:
        selected = selected[: int(limit)]
    invalid = [ep for ep in selected if ep < 0 or ep >= num_sources]
    if invalid:
        raise ValueError(f"Episode indices out of range [0, {num_sources}): {invalid}")
    return selected


def _write_env(path: Path, rows: list[dict[str, Any]]) -> None:
    lines = [
        "# Source this file before sbatch. Generated by make_contact_relabel_specs.py.",
        f"export SPEC_COUNT={len(rows)}",
    ]
    for idx, row in enumerate(rows):
        lines.append(f"export SPEC_{idx}={shlex.quote(row['spec'])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metadata", required=True, type=Path, help="Base lowdim dataset .metadata.json")
    parser.add_argument("--output-env", required=True, type=Path, help="Sourceable shell env output")
    parser.add_argument("--output-json", required=True, type=Path, help="Machine-readable manifest output")
    parser.add_argument("--episode", action="append", type=int, default=None, help="Episode index to include")
    parser.add_argument("--limit", type=int, default=None, help="Optional first-N episode limit")
    parser.add_argument("--episode-step", type=int, default=260)
    parser.add_argument("--reset-alpha", type=float, default=0.75)
    parser.add_argument(
        "--local-curobo-root",
        type=Path,
        default=None,
        help="Local root corresponding to --container-curobo-root; inferred from metadata if omitted.",
    )
    parser.add_argument("--container-curobo-root", default="/results/dp_bc/curobo_plans")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metadata_path = args.metadata.expanduser().resolve()
    payload = json.loads(metadata_path.read_text(encoding="utf-8"))
    sources = payload.get("sources")
    if not isinstance(sources, list) or not sources:
        raise ValueError(f"{metadata_path} does not contain a non-empty sources list")

    if args.local_curobo_root is None:
        first_path = Path(str(sources[0]["path"])).expanduser()
        parts = first_path.parts
        if "curobo_plans" not in parts:
            raise ValueError("Cannot infer --local-curobo-root from first source path")
        idx = parts.index("curobo_plans")
        local_curobo_root = Path(*parts[: idx + 1])
    else:
        local_curobo_root = args.local_curobo_root.expanduser().resolve()

    selected = _selected_episode_indices(len(sources), args.episode, args.limit)
    rows: list[dict[str, Any]] = []
    for spec_idx, episode in enumerate(selected):
        source = sources[episode]
        source_path = str(source.get("path", ""))
        if not source_path:
            raise ValueError(f"source {episode} has no path")
        trajectory = _container_path(
            source_path,
            local_curobo_root=local_curobo_root,
            container_curobo_root=str(args.container_curobo_root),
        )
        spec = f"{episode}:{int(args.episode_step)}:{trajectory}:{float(args.reset_alpha):g}"
        rows.append(
            {
                "spec_index": spec_idx,
                "episode": episode,
                "episode_step": int(args.episode_step),
                "reset_alpha": float(args.reset_alpha),
                "trajectory": trajectory,
                "spec": spec,
                "source_path": source_path,
                "run_name": source.get("run_name"),
                "frames_selected": source.get("frames_selected"),
            }
        )

    args.output_env.expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
    args.output_json.expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
    _write_env(args.output_env.expanduser().resolve(), rows)
    manifest = {
        "metadata": str(metadata_path),
        "local_curobo_root": str(local_curobo_root),
        "container_curobo_root": str(args.container_curobo_root),
        "episode_step": int(args.episode_step),
        "reset_alpha": float(args.reset_alpha),
        "spec_count": len(rows),
        "rows": rows,
    }
    args.output_json.expanduser().resolve().write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print("FRANKA_CUBE_CONTACT_RELABEL_SPECS " + json.dumps({"spec_count": len(rows)}, sort_keys=True))


if __name__ == "__main__":
    main()
